fix(eslint-plugin): [no-deprecated] max callstack exceeded when class implements itself
typescript-eslint/typescript-eslint pull request #10040
Opened 2024-09-23 13:40 UTC by tarunrajput

## PR Checklist

- [x] Addresses an existing open issue: fixes #10031
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

wraps `getJsDocTags` call in a try-catch

2024-09-24 16:13 UTC, kirkwaiblinger requested changes

2024-09-24 16:13 UTC, kirkwaiblinger commented on packages/eslint-plugin/src/rules/no-deprecated.ts
> +      try {
Let's try to be as surgical about the try/catch as we can - can we make it so that essentially _only_ the `getJsDocTags()` call is wrapped?

2024-09-24 16:13 UTC, kirkwaiblinger commented on packages/eslint-plugin/src/rules/no-deprecated.ts
let's add the test case from the issue to the `valid` cases in packages/eslint-plugin/tests/rules/no-deprecated.test.ts with a note that it's just there to ensure it doesn't crash and link the github issue https://github.com/typescript-eslint/typescript-eslint/issues/10031.

2024-09-24 16:13 UTC, kirkwaiblinger commented on packages/eslint-plugin/src/rules/no-deprecated.ts
> +        return;
could you add a comment that says something like `// workaround for https://github.com/microsoft/TypeScript/issues/60024`?

2024-09-27 23:04 UTC, kirkwaiblinger commented
awesome, thanks! 🙂 

<img alt="gif about infinite loop" src="https://media2.giphy.com/media/xThuWu82QD3pj4wvEQ/giphy.gif"/>

2024-09-27 23:04 UTC, kirkwaiblinger approved these changes

2024-09-28 08:56 UTC, auvred approved these changes
Thanks!

2024-09-29 22:44 UTC, merged