fix(type-utils): handle external packages that are not in `program.sourceFileToPackageName`
typescript-eslint/typescript-eslint pull request #10097
Opened 2024-10-03 13:12 UTC by abrahamguo

## PR Checklist

- [x] Addresses an existing open issue: fixes #10089 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

- For some reason, some `.d.ts` files are not included in TypeScript's `program.sourceFileToPackageName` map.
- Therefore, this causes types in those files to be unable to be matched via `{ from: 'package' }` `TypeOrValueSpecifier`s.
- The change to use `program.sourceFileToPackageName` was introduced in #6868 => #6870.
- To fix this regression, I restored the old logic from before #6870, and applied it conditionally if the declaration is not found in `program.sourceFileToPackageName`. I cannot see any issues that would arise from doing this.

2024-10-10 19:20 UTC, JoshuaKGoldberg requested changes
Seems like a reasonable direction given TypeScript's weirdness. But we'll have to work with custom `typeRoots`, I think.

🚀

2024-10-10 19:20 UTC, JoshuaKGoldberg commented on packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts
> +  );
https://www.typescriptlang.org/tsconfig/#typeRoots - if someone customizes this, then `fileNameMatcher` will be wrong. This'll need to reflect the project's `compilerOptions.typeRoots`.

2024-11-10 16:59 UTC, JoshuaKGoldberg commented
👋 Just checking in @abrahamguo, anything we can help with?a

2024-11-10 23:31 UTC, abrahamguo commented
Should be ready for review now, sorry for the delay! The remaining CI failures come from `main`.

2024-11-22 15:44 UTC, JoshuaKGoldberg commented on packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts
> +    `@types/${packageName.replace(/^@([^/]+)\//, '$1__')}`,
[Bug] `@types/` should not be hardcoded to always be considered. From https://www.typescriptlang.org/tsconfig/#typeRoots:

> If `typeRoots` is specified, _only_ packages under `typeRoots` will be included.

2024-11-22 15:45 UTC, JoshuaKGoldberg commented on packages/type-utils/src/typeOrValueSpecifiers/typeDeclaredInPackageDeclarationFile.ts
> +  );
(moved to https://github.com/typescript-eslint/typescript-eslint/pull/10097/files#r1854146022 to be closer to implementation)

2024-11-22 15:45 UTC, JoshuaKGoldberg requested changes
There's a pending [Bug], I believe?

2024-12-31 21:06 UTC, JoshuaKGoldberg commented
👋 Hey @abrahamguo! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging.

2025-01-02 00:29 UTC, abrahamguo commented
No, unfortunately I don't have time at the moment to finish this up!

2025-01-07 14:12 UTC, JoshuaKGoldberg commented
👍 No problem, thanks for getting it started! Closing out then.

If anybody wants to continue this work, please do! And if it builds off this PR, please add a co-author attribution.

2025-01-07 14:12 UTC, closed without merging