feat(eslint-plugin): [await thenable] check Promise.all
typescript-eslint/typescript-eslint pull request #10282
Opened 2024-11-04 23:14 UTC by Zamiell

## PR Checklist

- [X] Addresses an existing open issue: fixes #1804
- [X] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [X] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

- I added logic for a new type of check for `Promise.all`, `Promise.allSettled`, and `Promise.race`. As discussed in the aforementioned issue, we are arbitrarily adding this to `await-thenable` instead of putting it in into a new rule.
- I did not put the new logic behind an option because of YAGNI principle. If that is required, I can add an option.
- The type verification part probably needs to be reviewed, since I am not sure of the best way to check that an arbitrary `ts.Type` matches the form of `Iterable<Promise<any>>`. So for now, I just check for the most common case with hard-coded names.

2024-11-10 19:15 UTC, JoshuaKGoldberg requested changes

2024-11-11 09:21 UTC, kirkwaiblinger commented
If we go with this PR, we should add co-author attributions to @abrahamguo and @Tjstretchalot for #10163 and #8094.

2024-11-11 09:46 UTC, kirkwaiblinger commented on packages/eslint-plugin/src/rules/await-thenable.ts
> +          node.callee.object.name === 'Promise' &&
Sadly, TS's `getIterationTypesOfIterable` is basically exactly what we'd need for this, but it's not exposed. Feel free to open an issue with TS if you have spare time! But, yeah, we'll need to find a solution in the meantime...

I was also wondering if we can do something roughly like
```ts
function getIteratedType(checker: ts.TypeChecker, type: ts.Type): ts.Type | undefined {
  const symbolIterator = tsutils.getWellKnownSymbolPropertyOfType(type, 'iterator', checker);
  if (symbolIterator == null) {
    return;
  }

  const symbolIteratorType = checker.getTypeOfSymbol(symbolIterator);
  const symbolIteratorCallSignatures = tsutils.getCallSignaturesOfType(symbolIteratorType);
  const returnTypes = symbolIteratorCallSignatures.map(signature => signature.getReturnType());
  // figure out how to make a union of these types or just return the list :shrug:
  return returnTypes
}
```

2024-11-11 09:48 UTC, kirkwaiblinger commented
> * The type verification part probably needs to be reviewed, since I am not sure of the best way to check that an arbitrary `ts.Type` matches the form of `Iterable<Promise<any>>`. So for now, I just check for the most common case with hard-coded names.

Sadly, TS's `getIterationTypesOfIterable` is basically exactly what we'd need for this, but it's not exposed. Feel free to open an issue with TS if you have spare time! But, yeah, we'll need to find a solution in the meantime...

I was also wondering if we can do something roughly like
```ts
function getIteratedType(checker: ts.TypeChecker, type: ts.Type): ts.Type | undefined {
  const symbolIterator = tsutils.getWellKnownSymbolPropertyOfType(type, 'iterator', checker);
  if (symbolIterator == null) {
    return;
  }

  const symbolIteratorType = checker.getTypeOfSymbol(symbolIterator);
  const symbolIteratorCallSignatures = tsutils.getCallSignaturesOfType(symbolIteratorType);
  const returnTypes = symbolIteratorCallSignatures.map(signature => signature.getReturnType());
  // figure out how to make a union of these types or just return the list :shrug:
  return returnTypes
}
```

As for checking whether something looks like a promise, we generally use the `tsutils.isThenableType()` function.

2024-11-11 09:49 UTC, kirkwaiblinger commented on packages/eslint-plugin/src/rules/await-thenable.ts
> +          if (typeName === 'Array' && typeArgName !== 'Promise') {
https://github.com/typescript-eslint/typescript-eslint/pull/10282#issuecomment-2467690788

2024-11-11 09:52 UTC, kirkwaiblinger commented on packages/eslint-plugin/src/rules/await-thenable.ts
> +          node.callee.object.name === 'Promise' &&
I think this comment is on the wrong line, see https://github.com/typescript-eslint/typescript-eslint/pull/10282/files#r1836229674

2024-12-02 14:58 UTC, JoshuaKGoldberg commented
👋 Hey @Zamiell! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging.

2024-12-31 21:04 UTC, JoshuaKGoldberg commented
👋 Checking in again @Zamiell, happy new year! Is this still on your radar?

2025-01-10 00:13 UTC, Zamiell commented
yeah i still plan to work on this when i get some more free time, i have been very sick lately

2025-03-02 07:02 UTC, JoshuaKGoldberg commented
Closing out to un-block the issue, as planned. Cheers!

2025-03-02 07:02 UTC, closed without merging