feat(eslint-plugin): [max-params]: add function overload and function type support
typescript-eslint/typescript-eslint pull request #10312
Opened 2024-11-09 10:32 UTC by developer-bandi

## PR Checklist

- [x] Addresses an existing open issue: fixes #10293
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Added support for the TSDeclareFunction and TSFunctionType types.

2024-11-10 19:27 UTC, JoshuaKGoldberg requested changes
Good start 🚀

2024-11-10 19:27 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/tests/rules/max-params.test.ts
[Testing] These are reasonable `invalid` cases, but they should have corresponding `valid` ones too. Could you add those in please?

2024-11-10 19:27 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/tests/rules/max-params.test.ts
> +function makeDate(m: number, d: number, y: number): Date;
```suggestion
declare function makeDate(m: number, d: number, y: number): Date;
```

2024-11-22 19:27 UTC, JoshuaKGoldberg approved these changes
🙌 looks great to me, thanks as always @developer-bandi!

2024-11-22 19:45 UTC, kirkwaiblinger approved these changes

2024-11-22 20:02 UTC, merged