fix(eslint-plugin): report deprecations used in default export
typescript-eslint/typescript-eslint pull request #10330
Opened 2024-11-14 12:22 UTC by wszydlak

## PR Checklist

- [X] Addresses an existing open issue: fixes #10327
- [X] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [X] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Report deprecations which are used in default exports - this is the way typescript compiler reports deprecations.

2024-11-14 15:18 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-deprecated.ts
[Testing] Unit tests please 😇 

https://typescript-eslint.io/contributing/pull-requests#testing-changes

2024-11-14 15:18 UTC, JoshuaKGoldberg requested changes
Thanks for starting this! 🙌

2024-11-14 20:04 UTC, wszydlak commented on packages/eslint-plugin/src/rules/no-deprecated.ts
Sure, added, however I decided to add only `invalid` case 👍

2024-11-15 14:12 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-deprecated.ts
Any reason not to add a `valid`? I think it'd be good to make sure the rule doesn't erroneously report on a non-deprecated `export default`.

2024-11-15 14:12 UTC, JoshuaKGoldberg requested changes
Good `invalid` test, thanks! Just asking about `valid`.

2024-11-15 17:31 UTC, wszydlak commented on packages/eslint-plugin/src/rules/no-deprecated.ts
As default exports are not checked by rule, there is no difference between  https://github.com/typescript-eslint/typescript-eslint/blob/746560aab8b8df6fed02219f03e866795cdc58c6/packages/eslint-plugin/tests/rules/no-deprecated.test.ts#L101 test. Do to not add additional valid test for longer CI scripts i decided not to add, but if you need i can add one.

2024-11-15 18:59 UTC, wszydlak commented on packages/eslint-plugin/src/rules/no-deprecated.ts
Done 👍

2024-11-16 04:07 UTC, JoshuaKGoldberg submitted a review, later dismissed
💯 thanks!

2024-11-16 06:11 UTC, wszydlak commented on packages/eslint-plugin/tests/rules/no-deprecated.test.ts
> +    `
Added additional valid test 🙂

2024-11-16 06:12 UTC, wszydlak commented on packages/eslint-plugin/tests/rules/no-deprecated.test.ts
> +    `
Added additional valid test 🙂

2024-11-16 06:32 UTC, kirkwaiblinger approved these changes
Thanks! 👍

2024-11-16 10:43 UTC, merged