fix(eslint-plugin): [no-unnecessary-type-assertion] handle literal types
typescript-eslint/typescript-eslint pull request #10523
Opened 2024-12-19 16:00 UTC by mdm317

## PR Checklist

- [x] Addresses an existing open issue: fixes #000
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Add case when cast type is a template literal or a union type that is string-like.

2024-12-30 17:04 UTC, JoshuaKGoldberg requested changes
LGTM! Just requesting changes on naming and removing the `noFormat`. Thanks!

2025-01-02 18:53 UTC, JoshuaKGoldberg submitted a review, later dismissed
🪨

2025-01-02 19:12 UTC, ronami requested changes
Looking great! Just requesting minor changes around testing 🏆

2025-01-05 07:43 UTC, mdm317 commented on packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
> +          isAssertionTypeTemplateLiteral ||
Thanks for the review. I think it would be better to simplify logic for this issue.

2025-01-05 19:29 UTC, ronami approved these changes
Thanks 👍

2025-01-06 02:21 UTC, merged

2025-01-06 06:27 UTC, ronami commented
This was on my mind, and I missed it when I reviewed the PR yesterday, but I did notice this one regression ([playground link](https://typescript-eslint.io/play/#ts=5.6.2&fileType=.tsx&code=MYewdgzgLgBNCGUCmAuGAiJAPADgSwCckATdGAHwxyTGLzAHMyBeKmux9AbgCgeAzAK5hgUPOBgBbePQAUAShgBvHjBhEoggmGWq1MKAE9qaBMhjwIGbPiKkKbWvSZ6Avr1dA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0YANrhsOOdA7RImgLoaAviGNA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false), [deploy preview playground link](https://deploy-preview-10523--typescript-eslint.netlify.app/play#ts=5.7.2&fileType=.tsx&code=MYewdgzgLgBNCGUCmAuGAiJAPADgSwCckATdGAHwxyTGLzAHMyBeKmux9AbgCgeAzAK5hgUPOBgBbePQAUAShgBvHjBhEoggmGWq1MKAE9qaBMhjwIGbPiKkKbWvSZ6Avr1dA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0ipWkOTJE0fJQ5N0UOdA7RI4MAF8QOoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)):

```ts
const state: "expired" | "pending" = "pending";

function main() {
  return {
    // correctly reported previously, now doesn't report
    type: state as "expired" | "pending"
  };
}
```

I'll open a separate issue about it.

2025-01-06 15:49 UTC, JoshuaKGoldberg commented
Ah, it's both class properties and object properties:

```ts
class Example {
  type = state as 'expired' | 'pending'
}
```

I'm going to go ahead and revert this - I think the logic will need to be more intricate.