No misused spread ii electric boogaloo
typescript-eslint/typescript-eslint pull request #10551
Opened 2024-12-26 17:11 UTC by JoshuaKGoldberg

## PR Checklist

- [x] Addresses an existing open issue: fixes #748
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Continuation of @StyleShit's #8509 as indicated in https://github.com/typescript-eslint/typescript-eslint/pull/8443#issuecomment-2466798013. 

Co-authored-by: @StyleShit

2024-12-27 17:58 UTC, omril1 commented on packages/eslint-plugin/docs/rules/no-misused-spread.mdx
> +  Spring enumeration behaviors in JavaScript around encoded characters are often surprising.
Typo :) Spring -> String

2024-12-27 20:04 UTC, ronami requested changes
Really excited to enable this on some of the projects I work on 🎉

2024-12-29 08:01 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-misused-spread.ts
> +      const type = getConstrainedTypeAtLocation(services, node.argument);
Added some tests 👍

2024-12-29 08:02 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/docs/rules/no-misused-spread.mdx
> +  Spring enumeration behaviors in JavaScript around encoded characters are often surprising.
Thanks!

2024-12-29 08:03 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-misused-spread.ts
> +        "Using the spread operator on a string can cause unexpected behavior. Prefer `String.split('')` instead.",
I really like the idea, but think it will end up being tricky like a lot of suggestion fixers. Would you be ok with it as a followup?

2024-12-29 08:11 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-misused-spread.ts
> +  );
Added a test for a union type.

2024-12-29 08:13 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-misused-spread.ts
> +}
👍 Added a unit test with a union type.

2024-12-29 18:36 UTC, ronami commented on packages/eslint-plugin/src/rules/no-misused-spread.ts
> +        "Using the spread operator on a string can cause unexpected behavior. Prefer `String.split('')` instead.",
Sure, that sounds great 👍

2025-01-07 20:24 UTC, ronami approved these changes
Looks amazing, thank you 🥇

2025-01-13 00:04 UTC, merged

2025-01-15 05:51 UTC, boris-petrov commented
Once I updated, I got a conflict with [unicorn/prefer-spread](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-spread.md). They link to a [comment](https://stackoverflow.com/questions/4547609/how-can-i-get-a-character-array-from-a-string/34717402#34717402) in SO where the first example is:

```js
// DO NOT USE THIS!
const a = '𝟘𝟙𝟚𝟛'.split('');
console.log(a);
// Output: ["�","�","�","�","�","�","�","�"]
```

So... who do I believe? :smile:

2025-01-15 09:57 UTC, bradzacher commented
As per our contributing guide - please don't comment on closed PRs. If you think the rule is wrong, please file an issue and we can discuss there.

2025-01-31 15:18 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-misused-spread.ts
> +        "Using the spread operator on a string can cause unexpected behavior. Prefer `String.split('')` instead.",
For posterity: #10642