chore(eslint-plugin): use `getConstraintInfo` in no-unnecessary-template-expression
typescript-eslint/typescript-eslint pull request #10578
Opened 2024-12-31 10:15 UTC by 43081j

Switches the `no-unnecessary-template-expression` rule to use `getConstraintInfo` internally.

Related #10569

Assuming I've done the right thing here, let me know and i'll happily do most of the others. I'm just using this as a way to get my head back into the codebase

## PR Checklist

- [x] Addresses an existing open issue: related #10569
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

2024-12-31 20:12 UTC, kirkwaiblinger requested changes

2024-12-31 20:12 UTC, kirkwaiblinger commented on packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
> +      if (constraintType == null) {
Could you ensure there's a test for this case, please? Incidentally, ensuring that we handling unconstrained generics properly is sort of the whole reasoning behind the change to `getConstraintInfo`, so it's working as intended hehe 😁 

I probably should have added this context to the issue description - I'll go do so now!

2025-01-01 20:48 UTC, kirkwaiblinger approved these changes
Nice! Thanks for sending this in!!

FYI it's not a big deal but, but for future reference we like to avoid force-pushing, see https://typescript-eslint.io/contributing/pull-requests/

2025-01-01 20:53 UTC, 43081j commented
Yep it helps keep a trail for reviews etc

I just happen to be working in a branch I cut a few more out of, so I've been rebasing a fair amount locally

2025-01-03 18:40 UTC, JoshuaKGoldberg approved these changes
Swell!

2025-01-03 18:40 UTC, merged