chore(eslint-plugin) migrate to vitest
typescript-eslint/typescript-eslint pull request #10579
Opened 2024-12-31 15:40 UTC by 43081j

## PR Checklist

- [x] Addresses an existing open issue: #7112
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

this is just one possible PR for migrating to vitest

we need to avoid an unreviewable, giant PR, so the following has been done in this one:

- only migrate eslint-plugin for now
- for docs snapshots, retain a similar format rather than moving to the standard one-snapshot-per-file
- for all other snapshots, just update the snapshot (since they only had one per file already)

2025-01-13 01:28 UTC, JoshuaKGoldberg commented
This is awesome, thanks for sending @43081j! I'd really like to dive in soon and see if we can get this merged. But we're a little swamped catching up on issues after the holiday & new year break, and this is a lot of changes. So it'll probably be a little while till we can take a deep look. 😬 

In the meantime, some notes:

* `eslint-plugin` is one of our biggest packages. Is there a reason you wanted to start with this, and not a smaller one like `eslint-plugin-internal` or `type-utils`?
* Codecov is reporting a significant % drop, which means coverage is probably not set up right with it - could you take a look please?
* Although we all would prefer to move away from implicit globals, adding in the `import { describe, it, ... } from 'vitest'` is adding a lot to the diff. Is there a reason not to enable [Vitest `globals`](https://vitest.dev/config/#globals) for now - with a followup to remove it later?

2025-01-13 10:28 UTC, 43081j commented
> eslint-plugin is one of our biggest packages. Is there a reason you wanted to start with this, and not a smaller one like eslint-plugin-internal or type-utils?

no particular reason, i just chose the package i was looking at at the time

> Codecov is reporting a significant % drop, which means coverage is probably not set up right with it - could you take a look please?

ill have a look

> Although we all would prefer to move away from implicit globals, adding in the import { describe, it, ... } from 'vitest' is adding a lot to the diff. Is there a reason not to enable [Vitest globals](https://vitest.dev/config/#globals) for now - with a followup to remove it later?

we could use `globals` but i would say the diff is actually mostly from snapshot changes than it is from imports.

i think without the snapshot changes, it'd be a pretty small diff. so i'd prefer to keep them, but let me know if you don't

2025-01-13 15:47 UTC, JoshuaKGoldberg commented
> i think without the snapshot changes, it'd be a pretty small diff. so i'd prefer to keep them, but let me know if you don't

+1 from me on the small diff 😄. I'd prefer not to keep them. The smaller the diff the better!

> if you could have a look at some point too, that'd be helpful

👍 ACK, we can help as part of the review if it's not figured out

2025-01-13 15:55 UTC, 43081j commented
> +1 from me on the small diff 😄. I'd prefer not to keep them. The smaller the diff the better!

what i meant was that the imports don't add much to the diff, since the only reason this is a "big PR" is the snapshot changes rather than those imports.

i'd rather keep the imports seeing as its where we want to be

if you diff without snapshots, its small (but of course we need those snapshot updates in this PR)

as for the coverage change, im pretty sure it is just vite doing a much better job by using v8 coverage. that and the added `tools/` directory seem to account for the difference

2025-01-13 17:43 UTC, ronami commented
+1 from me on having the smallest diff possible. Since this is already a big change, having it be gradual is a big plus. I think that moving from [Vitest `globals`](https://vitest.dev/config/#globals) to using imports can be done separately on a future PR, which would help not miss anything on this PR.

2025-01-18 16:22 UTC, 43081j commented
i've now switched to using globals

we need to re-open #10582 and land #10680 before this

2025-01-20 10:09 UTC, kirkwaiblinger requested changes
As mentioned in https://github.com/typescript-eslint/typescript-eslint/pull/10680#issuecomment-2601969922 would you mind please removing the unrelated `test()` -> `it()` changes?

2025-01-28 18:49 UTC, JoshuaKGoldberg commented on packages/typescript-eslint/package.json
> +    "test": "jest --passWithNoTests",
Oh, we don't need `--passWithNoTests` anymore. The package actually has tests now as of #10333. I forgot this was here 😄

2025-01-28 19:09 UTC, JoshuaKGoldberg requested changes
OK! This is looking great - just a few changes left to iron out.

Despite the large file count, this really didn't impact all that many different types of files. 251 of them were schema snapshots. I looked at around a half dozen of each folder of those and then ran this to mark them as viewed locally:

```js
const fileInfos = Array.from(document.querySelectorAll(`.file-info`)).filter(
  (node) => node.textContent.trim().endsWith(".shot")
);

console.log(fileInfos.length, "schema snapshots");

for (const fileInfo of fileInfos) {
  const input = fileInfo.parentElement.parentElement.querySelector(
    "input[type=checkbox]"
  );

  if (!input.checked) {
    input.click();
  }
}
```

2025-01-29 00:19 UTC, 43081j commented
have caught up from main and applied the suggestions 👍

2025-01-30 16:51 UTC, JoshuaKGoldberg submitted a review, later dismissed
🚀 This looks great to me, thanks a million for sticking with it! Love to see the +2.3k 🟩 -4.3k 🟥. 

We should definitely get review from another team member such as @kirkwaiblinger given how they've been looking at it & it's a pretty important change.

Also marking this blocked as resolving the `test-coverage` / `test --coverage` discussion #10582.

2025-02-27 22:27 UTC, aryaemami59 commented on packages/eslint-plugin/vitest.setup.ts
This doesn't seem to be necessary.

2025-03-22 20:46 UTC, kirkwaiblinger commented on packages/eslint-plugin/package.json
> +    "test": "vitest run",
Let's align these with the other vitest PRs?
```suggestion
    "test": "vitest --run --config=$INIT_CWD/vitest.config.mts",
```

2025-03-22 20:46 UTC, kirkwaiblinger commented on packages/eslint-plugin/package.json
> +    "test-single": "vitest run",
```suggestion
    "test-single": "vitest --run --config=$INIT_CWD/vitest.config.mts",
```

2025-03-22 20:47 UTC, kirkwaiblinger approved these changes
Looks good to me!

2025-03-22 20:48 UTC, kirkwaiblinger commented on eslint.config.mjs
> +    },
refer to https://github.com/typescript-eslint/typescript-eslint/pull/10978#discussion_r2007453476

2025-03-23 09:46 UTC, 43081j commented on packages/eslint-plugin/package.json
> +    "test": "vitest run",
Do we know why? 

We should be able to run `vitest run` in all of them and auto discover the config

Is vitest not discovering mts config?

2025-04-14 16:28 UTC, JoshuaKGoldberg commented
Starting to see this once in a while:

```plaintext
Error: Test timed out in 5000ms.
If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".
```

https://cloud.nx.app/runs/EisURTJuXm/task/eslint-plugin%3Atest

Something to keep an eye on...

2025-04-14 20:46 UTC, merged