chore: add test-coverage script
typescript-eslint/typescript-eslint pull request #10582
Opened 2024-12-31 17:38 UTC by 43081j

Adds a `test-coverage` script to each package.

With this change, each package has these two scripts:

- `test` - run tests with coverage disabled
- `test-coverage` - run tests with coverage enabled (_if_ the package wants to support coverage)

Before this change, `test` behaved like `test-coverage` (i.e. packages had coverage enabled in it). In CI, we then forced coverage off in some situations by passing a flag: `npm run test -- --coverage=false`.

This resulted in commands like `jest --coverage --coverage=false`.

While jest is happy with this, vitest is not. Given we are likely to move to vitest, it is worth fixing this ahead of time.

## PR Checklist

- [ ] Addresses an existing open issue: **none since this is an infra/repo thing spotted in another PR**
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

2025-01-03 23:43 UTC, kirkwaiblinger commented
Hey @43081j , we do need to ask that you follow the template and [contributing guide](https://typescript-eslint.io/contributing/pull-requests) 
```text
- Only send pull requests that resolve [open, unassigned issues marked as accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aissue+is%3Aopen+label%3A%22accepting+prs%22+no%3Aassignee)
   - One exception: extremely minor documentation typos
```

For something like this please file an issue so we can discuss

2025-01-03 23:45 UTC, kirkwaiblinger commented
> For something like this please file an issue so we can discuss

_Do_ feel free to link a _draft_ PR on the issue, though, if it's a helpful aid to the discussion

2025-01-04 00:43 UTC, 43081j commented
No worries

As mentioned, this came out of a related PR so didn't have it's own issue. Happy to make one, the guidelines certainly were read, I just didn't realise this needed it's own issue 

Will keep the branch around since it is likely we will need it

2025-01-04 00:50 UTC, 43081j commented
#10607

2025-01-20 10:11 UTC, kirkwaiblinger commented
reopening following discussion in https://github.com/typescript-eslint/typescript-eslint/pull/10579 and https://github.com/typescript-eslint/typescript-eslint/issues/7112#issuecomment-2598914511

2025-01-20 14:22 UTC, 43081j commented
in the various PRs by @aryaemami59, an environment variable has been used instead of having two scripts.

that may make more sense, if we don't care about being able to locally run with coverage (and instead we'd manually pass `--coverage` when we run it ourselves)

if we do that, i'm happy to update this PR to make use of the `COLLECT_COVERAGE` env var we already have in our CI

either way, we remove the `--coverage` flag. we just need to decide if we'd rather have runnable scripts or an env variable

2025-01-21 20:05 UTC, aryaemami59 commented
@43081j Honestly I think a `test-coverage` script would be better and will probably cause less issues as it's more explicit and can be used more reliably locally.

2025-01-23 15:36 UTC, 43081j commented
@kirkwaiblinger @JoshuaKGoldberg any chance we can get some movement on this?

it will unblock the rest of the vitest work. there are still pieces of the larger PRs that can be cut out into individual changes, but this needs to land first

2025-01-23 15:54 UTC, JoshuaKGoldberg commented
For visibility, I'm stuck doing a few other projects this week - but if nobody's moved it forward by early next week I can try to find some time. Thanks for pushing on it! ❤️

2025-01-23 17:33 UTC, kirkwaiblinger commented
Hey! I also am not able to dive into this area at the moment, several things going on in my personal life and such. I expect it will be at least until the weekend but potentially next week. We definitely appreciate your work on this and do plan to unblock you as soon as we can. Thanks for understanding! 🙏

2025-01-28 18:15 UTC, JoshuaKGoldberg requested changes
Thanks for pushing on this! I _think_ the general direction of removing `--coverage` out of the `test` scripts is good. One request that's blocking: I think we can unify them altogether to not mention `--coverage` in `package.json`s at all, once `ast-spec` is fixed?

2025-01-28 23:29 UTC, 43081j commented on .github/workflows/ci.yml
> +      # test-coverage script on purpose
this was just me copying how it already is. so im not sure why coverage would be disabled on certain packages

you're probably right that its to do with those errors

we can't add `--coverage` to `test` because of the other comment above this one (the fact that we want to only run coverage on current node, not all node versions in the matrix)

2025-01-28 23:40 UTC, 43081j commented on .github/workflows/ci.yml
> +      # test-coverage script on purpose
i've done what you suggested and removed the comment 👍

2025-01-30 16:49 UTC, JoshuaKGoldberg requested changes
Progress!

2025-01-30 16:51 UTC, 43081j commented on packages/scope-manager/package.json
> +    "test-coverage": "npx nx test --code-coverage",
Yep one of them was or is missing jest as a dependency, and npx was allowing it to use the root one

May not be the case here but I'd just change it to use jest directly if you're ok with that

2025-01-30 16:52 UTC, JoshuaKGoldberg commented on packages/scope-manager/package.json
> +    "test-coverage": "npx nx test --code-coverage",
👍 from me

2025-01-30 22:17 UTC, 43081j commented on .github/workflows/ci.yml
> +        run: npx nx run ${{ matrix.package }}:test-coverage
are you sure? part of this was also so local development can `npm run test-coverage`, not caring what test runner or flags it takes

you're only looking at CI here, not at local dev.

if we do what you suggest, it means local dev needs to remember to do `npm test -- --coverage` or some such thing. is that what you intend?

if so im happy to change it, but it seemed like having a script was useful

2025-01-31 15:45 UTC, JoshuaKGoldberg commented on .github/workflows/ci.yml
> +        run: npx nx run ${{ matrix.package }}:test-coverage
That's exactly what I'm intending, yes. Once all the packages are aligned to have the same `test` script then it'll be the same `-- --coverage` always. At the cost of a few more characters to type when running tests _with_ coverage locally, we'll have one less line in each `package.json`.

2025-02-01 13:27 UTC, JoshuaKGoldberg submitted a review, later dismissed
🔥 thanks, this is looking great!

2025-02-02 21:38 UTC, kirkwaiblinger requested changes
I think this looks to be in good shape. The one request would be to please update the title and PR description with the amended approach, so that we have a good reference for this going forward. If I understand correctly, the outcome was essentially
- Keep a single "test" script for each package, allowing the coverage to be overridden by passed-in `-- --coverage=(true|false)` variable (fixing the commands so that passing such a variable actually works as expected)
- Coverage will be disabled (or enabled?) by default when running `yarn test` on the whole repo (and is there a difference in this behavior between `yarn test` vs `yarn workspace foo test`?)

Thanks for sifting through this!

2025-02-02 22:01 UTC, 43081j commented
done

coverage is disabled everywhere. you must enable it explicitly by passing `--coverage` (which is exactly what CI does)

2025-02-05 04:37 UTC, kirkwaiblinger commented
Awesome, thanks for updating the details! But now that the expected behavior is very clear, I am wondering whether this is working correctly... Based on the following steps, 

1. Check out this PR branch
2. `git clean -xfd` (completely clean repo state)
3. `yarn`
4. `yarn test`

I observe on my machine that the coverage dirs are created and populated in the various packages locally (to name a few concretely: eslint-plugin, eslint-plugin-internal, parser, ...), but I expect them not to be. Does this occur for you as well? I'm assuming it's a bug if it does?

2025-02-05 04:39 UTC, kirkwaiblinger reviewed
(leaving a "review" for automation purposes)

2025-02-05 04:50 UTC, kirkwaiblinger requested changes
Had a poke around - I think this might be the issue?

https://github.com/typescript-eslint/typescript-eslint/blob/f8bdb494cfeb938157a29b4a923aaf4fc9d330d8/jest.config.base.js#L9

From a glance, there's a few jest configs around the repo that might need to be double-checked.

2025-02-05 09:19 UTC, 43081j commented
Not too sure, I'll remove the flag though

Would be good to get this over the line soon as the longer we leave it, the more conflicts and catch ups I have to deal with

2025-02-25 13:41 UTC, 43081j commented
@kirkwaiblinger i think disabling the flag sorted what you were seeing

can you double check?

2025-02-25 14:01 UTC, JoshuaKGoldberg reviewed
I'll defer to Kirk for a full review, just posting to get you feedback quickly - I think we can trim away just a bit more?

2025-02-27 06:12 UTC, kirkwaiblinger requested changes
I think we're very close! Important blocker for me is just that `yarn test` and `yarn test -- --coverage` must both pass locally.

2025-02-27 06:12 UTC, kirkwaiblinger commented on packages/rule-schema-to-typescript-types/package.json
> +    "test": "npx jest",
Running simply `yarn test` locally, I get an error due to there not being any tests in this package. I think we can just safely remove it? 

```suggestion
```

Not sure whether an  `exclude` from the root `package.json` `test` script is also beneficial but it doesn't seem to be required.

2025-02-27 06:12 UTC, kirkwaiblinger commented on packages/ast-spec/jest.config.js
Is the `collectCoverage: false` in this file intentional to still be there? if I run `yarn test -- --coverage` it does produce coverage (presumably the env variable overrides the variable here). But I'm wondering if it's anyway superseded by the addition of the `coveragePathIgnorePatterns`?

2025-02-27 06:16 UTC, kirkwaiblinger commented on packages/ast-spec/jest.config.js
Oh - Looks like change was requested in both https://github.com/typescript-eslint/typescript-eslint/pull/10582#discussion_r1932650393 and https://github.com/typescript-eslint/typescript-eslint/pull/10582#discussion_r1969808358 lol. Maybe forgot to push?

2025-02-27 07:28 UTC, 43081j commented on packages/ast-spec/jest.config.js
I don't know anymore. Too much back and forth. 

Looks correct now however we got there

2025-02-27 07:33 UTC, 43081j commented
Looks good to me. If there are any other changes, please do just push them so we can get this merged and reduce the iteration time

Will be good to get this merged 👍

2025-02-27 14:49 UTC, merged

2025-02-27 14:51 UTC, kirkwaiblinger commented
@43081j Excited to be merging! Thanks for your work on this!