fix(eslint-plugin): [no-shadow] false positive in conditional types
typescript-eslint/typescript-eslint pull request #2537
Opened 2020-09-10 19:44 UTC by dinofx

This fixes #2526 
In a conditional type, the inferred types are not in scope in the "if false" type.

2020-09-13 19:20 UTC, bradzacher requested changes
Fix itself LGTM!

----

To help prevent regressions, could you please add a new snapshot test into `packages/scope-manager/tests/fixtures/type-declaration`
Call it something like `conditional-nested.ts`

The test should be something like:

```ts
type Test<T> = T extends Array<infer U>
  ? U
  : T extends Set<infer U>
  ? U
```

Then you can `cd pacakges/scope-manager && yarn test fixtures -u` to update the snapshot.
What we're looking for here is a snapshot wherein there are two separate `U` variables created each with their own reference.

If you're not sure what to look for, just push the snapshot and I will be able to verify it.

2020-09-13 19:20 UTC, bradzacher commented on packages/scope-manager/src/referencer/TypeVisitor.ts
> +    this.visitChildren(node, ['falseType']);
```suggestion
    // type parameters inferred in the condition clause are not accessible within the false branch
    this.visitChildren(node, ['falseType']);
```

2020-09-14 15:08 UTC, dinofx commented
Added the new fixture and snapshot

2020-09-16 13:42 UTC, dinofx commented
@bradzacher are any other changes needed?

2020-09-16 16:10 UTC, bradzacher approved these changes
LGTM - thanks for doing this!

2020-09-16 16:11 UTC, merged