fix(eslint-plugin): updated rule for interface in module declaration
typescript-eslint/typescript-eslint pull request #2678
Opened 2020-10-15 18:44 UTC by aggmoulik

Signed-off-by: Moulik Aggarwal <qwertymoulik@gmail.com>

2020-10-15 18:53 UTC, aggmoulik commented
Fixes #2340

2020-10-18 18:55 UTC, bradzacher requested changes
the logic itself LGTM - just two comments.
thanks for working on this!

2020-10-18 18:55 UTC, bradzacher commented on packages/eslint-plugin/src/rules/method-signature-style.ts
> +    }
We can remove the `any` here with the catch-all `Node` type

```suggestion
    function isNodeParentModuleDeclaration(node: TSESTree.Node): boolean {
      if (!node.parent) {
        return false;
      }
    
      if (node.parent.type === AST_NODE_TYPES.TSModuleDeclaration) {
        return true;
      }

      if (node.parent.type === AST_NODE_TYPES.Program) {
        return false;
      }
      
      return isNodeParentModuleDeclaration(node.parent);
    }
```

2020-10-18 18:55 UTC, bradzacher commented on packages/eslint-plugin/tests/rules/method-signature-style.test.ts
> +      `,
indent the example one line, and then you can use the fixer to auto-format the code block
```suggestion
      code: `
        declare global {
          namespace jest {
            interface Matchers<R, T> {
              // Add overloads specific to the DOM
              toHaveProp<K extends keyof DomPropsOf<T>>(name: K, value?: DomPropsOf<T>[K]): R;
              toHaveProps(props: Partial<DomPropsOf<T>>): R;
            }
          }
        }
      `,
```

2020-10-19 06:49 UTC, aggmoulik commented
Hy @bradzacher , I have updated things you suggested.

2020-10-19 17:06 UTC, bradzacher approved these changes
LGTM - thanks for your contribution!

2020-10-19 17:09 UTC, merged

2020-10-20 15:17 UTC, aggmoulik commented
Hy @bradzacher, Can you please add `hacktoberfest-accepted` label here.

2020-10-20 15:42 UTC, bradzacher commented
I thought they only need a tag if they weren't going to be merged in October?