feat(eslint-plugin): add reference on how to type an empty object in `ban-types`
typescript-eslint/typescript-eslint pull request #2758
Opened 2020-11-12 13:39 UTC by martinfrancois

I recently got a `ban-types` error when specifying an empty object to be allowed, which correctly warned me that this is not what I intended. But the message only offered alternatives for cases that didn't apply to my case in particular. After a lot of digging I found this issue (https://github.com/typescript-eslint/typescript-eslint/issues/2063) thankfully explaining the solution to my problem.

I want to save some other devs the trouble of having to look for a solution in this case (or even worse, some people probably ignoring the error, should they not find a solution). This was also suggested here https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-659748424

2020-11-13 19:47 UTC, bradzacher requested changes

2020-11-13 19:47 UTC, bradzacher commented on packages/eslint-plugin/docs/rules/ban-types.md
> +  - See [microsoft/TypeScript#2063](https://github.com/typescript-eslint/typescript-eslint/issues/2063).
microsoft/TypeScript#2063
```suggestion
  - See [this comment for more information](https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492).
```

2020-11-13 19:47 UTC, bradzacher commented on packages/eslint-plugin/src/rules/ban-types.ts
> +      '  type EmptyObject = NoElements<Record<string, never>>;',
```suggestion
      '- If you want a type meaning "empty object", you probably want `Record<string, never>` instead.',
```

2020-11-16 22:44 UTC, martinfrancois commented
@bradzacher thanks for the suggestions! I applied them.

2020-11-17 18:18 UTC, bradzacher approved these changes
thanks!

2020-11-17 18:18 UTC, merged