docs(eslint-plugin): [explicit-module-boundary-types] fix doc & code examples
typescript-eslint/typescript-eslint pull request #3058
Opened 2021-02-14 19:44 UTC by MrChocolatine

1. For each option of the rule, the sentences `Examples of incorrect/correct code for this rule with ...` were wrong when the option's value had to be `false`.

2. Slight simplification of a few code examples, less confusing.

3. Fix and homogenise code examples.

2021-02-14 20:11 UTC, bradzacher requested changes
thanks!
you'll need to format the docs appropriately using prettier

2021-02-14 20:17 UTC, MrChocolatine commented
@bradzacher Yes I just saw that. I made the change on GitHub directly but I will run Prettier as soon as I can run it on my laptop.
However I am still surprised as I thought I kept the current code style... We will see.

2021-02-14 20:19 UTC, bradzacher commented
Probably just needs a new line somewhere.

Easiest way to fix it without checking out is to copy paste the file into the prettier demo on their website (just gotta make sure the settings match our config)

2021-02-14 21:38 UTC, MrChocolatine commented
@bradzacher prettier executed ✅ . Weird, I sincerely thought the previous code was less readable but ¯\_(ツ)_/¯ .

2021-02-14 21:44 UTC, armano2 approved these changes

2021-02-15 02:14 UTC, bradzacher approved these changes
yeah that's an issue they've recently fixed but haven't yet released.
https://github.com/prettier/prettier/issues/8840

2021-02-15 02:14 UTC, merged