feat(eslint-plugin): [no-unnecessary-type-assertion] use getContextualType directly
typescript-eslint/typescript-eslint pull request #3133
Opened 2021-03-02 15:59 UTC by Zzzen

should fix #2953

This is an aggressive move, but I don't why we don't use getContextualType directly. All current tests have passed. If this is feasible, I can add more test cases.

2021-03-02 16:25 UTC, Zzzen commented
It is weird CI is failing to install dependencies.

2021-03-02 16:26 UTC, armano2 commented
its unrelated to your change

2021-03-02 18:52 UTC, bradzacher requested changes
The `getContextualType` function was first added in #478 (and was moved to a shared util in #1644).

I'll be honest when I say that I don't remember why I added it - I vaguely remember that there were a number of issues with `getContextualType`.
The fact that there's a lint error now that you've removed this logic says that it's still the case that `checker.getContextualType` is not infallible.

2021-03-03 16:16 UTC, Zzzen commented
👌 👌 got it

2021-03-08 17:35 UTC, bradzacher approved these changes
LGTM - thanks for your contribution!

2021-03-08 17:35 UTC, merged

2021-03-15 09:46 UTC, danielrentz commented
@Zzzen @bradzacher This change breaks some code in our project, just want to ask back how you consider the following (simplified) example:
```ts
class X {
    public doSomething();
}
// ...
const arr: X[] = [];
// ...
let x: X | undefined;
if (arr.length > 0) {
    x = arr.pop()!; // <== known that pop() returns something, needed to temp. narrow `x`
    x.doSomething();
}
// ...
if (x) {
    // ...
}
```

2021-03-15 15:41 UTC, bradzacher commented
@danielrentz please file a new issue instead of commenting on old PRs.