fix(eslint-plugin): [explicit-module-boundary-types] fixes #2864 related to functions in nested object properties
typescript-eslint/typescript-eslint pull request #3178
Opened 2021-03-12 16:11 UTC by grumd

Fixes #2864

**Gist of it:**

`explicit-module-boundary-types` and `explicit-function-return-type` both have an option `allowTypedFunctionExpressions`.
It makes this code correct:
```ts
interface ObjectType {
  foo(): number;
}
export const obj: ObjectType = {
  foo: () => 1,
};
```

The issue is that the following code is not correct even with the option set to `true`:
```ts
interface ObjectType {
  foo: { bar: () => number }; 
}
export const obj: ObjectType = {
  foo: { bar: () => 1 },
};
```

My PR fixes the issue for both of these rules and adds relevant tests.

My fork can be used with npm/yarn using this, that's what I temporarily will do.
```
"@typescript-eslint/eslint-plugin": "https://gitpkg.now.sh/grumd/typescript-eslint/packages/eslint-plugin?build",
```

2021-03-12 16:39 UTC, armano2 approved these changes

2021-03-12 16:39 UTC, armano2 requested changes
can you add unit test for `explicit-module-boundary-types`

2021-03-12 17:36 UTC, grumd commented
> can you add unit tests for `explicit-module-boundary-types`

Added

2021-03-15 08:12 UTC, bradzacher approved these changes
thanks!

2021-03-15 08:13 UTC, merged