feat(typescript-estree): support override modifer for parameter property
typescript-eslint/typescript-eslint pull request #3485
Opened 2021-06-06 04:36 UTC by sosukesuzuki

ref: https://github.com/prettier/prettier/issues/11017

Support TS 4.3 `override` modifier for parameter properties.

[TS Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBC0G8BQ1XWAewHYQC4CcBXYXDfACgAd8NcBTEugE2nzrCexAE91sAzAJYBzAFyJoYcXnyCswgNzQARuKyEAtsrr5oAXwCUiFGj1IzSUJBgARaHQAe9LExjxkqTDgLFSFarQM9CzQGABuOrJMdKhsHFy8fFhCYhJS0DJyiipqmtq6hsZoGYSUOuReKQYKJmZmQA)

2021-06-06 04:37 UTC, sosukesuzuki commented on packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
> +     * SyntaxError: Unexpected token, expected ","
babel/parser cannot parse override modifier for parameter properties, I'll report and fix it.

2021-06-06 08:53 UTC, bradzacher commented
I'm not sure about this. It currently is an explicit TS error, so I think that babel has it right.

This should probably be a syntax error, and something we shouldn't support explicitly.

I think this is another case where prettier could access the underlying TS ast to look for the existence of a bad modifier (until such time that we have support for syntax errors?)

2021-06-06 09:21 UTC, sosukesuzuki commented
For example, in this case the override modifier of the parameter property is required. [TypeScript Playground Link](https://www.typescriptlang.org/play?noImplicitOverride=true&strict=true#code/MYGwhgzhAEBC0G8BQ1XQA4FcBGICWw02YAXgFzQB2mAttgKYBO0AvNAIwDcKawA9pQgAXRpmBC+jABRZcBaADM+fCsMZ5KAcwA0GHPkLFGFanSYBKRD1QBfJHaShIMACLR6ADyH1KAExjwyGh6coR8AG5M6r70qEYmtAzMbOzW0AD06dARUXgx0Iz0AI6YeIW+0AD8afyCImIS0rIGisqqIho6IS3E5FSJFlbBwRCY6ExSSny6ACwATOZpdnZAA)
Also in TypeScript complier, override modifier for parameter property is allowed explicitly. (ref: https://github.com/microsoft/TypeScript/pull/43831)

2021-06-06 09:26 UTC, bradzacher commented
OH! I see.
https://github.com/microsoft/TypeScript/pull/43831 was released as part of the RC.

When I built the feature, I used the playground to figure out what was supported.
The playground doesn't ever use the RC version, so I was working against `4.3-beta`.
So when I tested the parameter property case, it was a TS error.

But that PR obviously makes it supported - and testing against 4.3.2 it does work without an error.
This is correct then.

2021-06-06 09:37 UTC, sosukesuzuki commented on packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
> +     * SyntaxError: Unexpected token, expected ","
https://github.com/babel/babel/issues/13427

2021-06-06 19:33 UTC, bradzacher requested changes
LGTM - one suggestion:
could you please add a test for this case with JUST the `override` as this emits as a parameter property:

```ts
class SpecializedComponent extends SomeComponent {
  constructor(override param: string) {
      super();
  }
}
```
[repl](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDKD2BbApgYSQB3gO2dgLtAN4BQ050GYATmIgFzQT7UCW2A5tALzQDkfANwkAviRKhIMWBmTBWYEKwBeyACbpEWXAWjIAHvjxrpSNJhx5CpcsBzNqAV2D541ABTwAbsmps1yJQ0dIwO7BwAlMRkFOQQjrIeEcLkYmJAA)

2021-06-06 19:33 UTC, bradzacher commented on packages/typescript-estree/src/convert.ts
> +              hasModifier(SyntaxKind.OverrideKeyword, node) || undefined,
I do hate that this emits `"override": undefined` if there isn't an override - but the entire node is built like this so 🤷‍♂️  it'll do for now.

We can revisit the entire AST later to fix this sort of weirdness and standardise on just emitting `false`.

2021-06-07 02:42 UTC, bradzacher approved these changes
thanks for this!

2021-06-09 05:57 UTC, merged