fix(eslint-plugin): [prefer-return-this-type]: handle generics propery in fixer
typescript-eslint/typescript-eslint pull request #3852
Opened 2021-09-07 17:44 UTC by rafaelss95

Fixes #3842.

2021-09-08 08:34 UTC, MichaelDeBoey submitted a review, later dismissed

2021-09-20 21:10 UTC, bradzacher requested changes
thanks for this! - one comment

2021-09-20 21:10 UTC, bradzacher commented on packages/eslint-plugin/src/rules/prefer-return-this-type.ts
> +            : classNameRef;
instead of doing this here - we should instead change the `tryGetNameInType` function to return the `TSTypeReference` instead of the identifier.

2021-09-21 06:42 UTC, bradzacher approved these changes
LGTM - thanks for fixing this!

2021-09-21 06:42 UTC, merged