fix(eslint-plugin): [no-require-imports] report only global 'require'
typescript-eslint/typescript-eslint pull request #3871
Opened 2021-09-12 03:56 UTC by rafaelss95

Fixes #3713.

2021-09-12 03:57 UTC, rafaelss95 commented on packages/eslint-plugin/src/rules/no-require-imports.ts
> +function getVariableByName(
This is a copy-paste from https://github.com/typescript-eslint/typescript-eslint/blob/4a88de2c621ae645c070d995768006df8cb7e4df/packages/eslint-plugin/src/rules/no-shadow.ts#L329-L346

2021-09-20 21:38 UTC, bradzacher requested changes
thanks for doing this!
a few comments

2021-09-21 01:43 UTC, rafaelss95 commented
> instead of copy-pasting it - let's move this to an internal util within the util folder and share the code.

> https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/src/util

Do you want me to do this in this PR (and also use it in `no-shadow`)?

2021-09-21 04:46 UTC, rafaelss95 commented on packages/eslint-plugin/src/rules/no-require-imports.ts
> +        if (!variable?.identifiers.length) {
`yarn check-spelling` complains about this:

<img width="454" alt="Userland" src="https://user-images.githubusercontent.com/11965907/134112895-e06ebb32-b359-4e59-8725-5cf04f36e0ee.png">

2021-09-21 06:25 UTC, bradzacher commented on packages/eslint-plugin/src/rules/no-require-imports.ts
> +        if (!variable?.identifiers.length) {
feel free to hyphenate it - `user-land` it should be fine with

2021-09-21 06:27 UTC, bradzacher commented
> (I can send another PR addressing this or maybe amend it to #3868). Let me know your thoughts.

Feel free to make another PR - keeps it clear and attributes each contribution to you :)

2021-09-21 06:44 UTC, merged