feat(utils): extract `isNotTokenOfTypeWithConditions` out of `ast-utils`' `predicates`
typescript-eslint/typescript-eslint pull request #4502
Opened 2022-02-01 11:55 UTC by MichaelDeBoey

This is the negative version of what I did in #3977

2022-02-01 11:55 UTC, MichaelDeBoey commented on packages/utils/src/ast-utils/helpers.ts
> +  ): token is Exclude<
Unfortunately, linting obliges me to add this type a second time 😢

2022-02-23 22:04 UTC, JoshuaKGoldberg approved these changes
❤️‍🔥

2022-02-23 22:35 UTC, JoshuaKGoldberg requested changes
Ah, actually, codecov is right - could you make sure these are unit tested please?

At least `isNotOptionalChainPunctuator` is duplicated in user code.

2022-02-24 00:38 UTC, MichaelDeBoey commented
@JoshuaKGoldberg The other helper functions also don't have any tests, so I think this is good to go as is?

2022-02-24 01:38 UTC, JoshuaKGoldberg commented
Hmm, I suppose so. It would be nice to have them be unit tested directly but I guess if none of them are we can have that as a followup issue. 🤷

2022-02-24 01:38 UTC, JoshuaKGoldberg commented
This one I definitely cannot merge without an adult's help:

![Screenshot of a failing GitHub status check blocking merge](https://user-images.githubusercontent.com/3335181/155440658-49c4a594-e6ad-43c1-a471-c3185fcb7c58.png)

2022-02-24 01:39 UTC, JoshuaKGoldberg approved these changes
✅

2022-02-24 01:39 UTC, JoshuaKGoldberg commented
This one I definitely cannot merge without an adult's help:

![Screenshot of failing expected checks blocking merge](https://user-images.githubusercontent.com/3335181/155440750-11eae45d-46c6-4f43-87c0-d59f7b7a4b37.png)

2022-02-24 05:35 UTC, merged