feat(eslint-plugin): added ignoreDifferentlyNamedParameters option to unified-signatures
typescript-eslint/typescript-eslint pull request #4659
Opened 2022-03-09 18:37 UTC by JoshuaKGoldberg

## PR Checklist

-   [x] Addresses an existing issue: fixes #2386
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

When two signatures have the same number of parameters, then two parameters having a different name means they won't be considered unifiable.

Also deduplicates a bit of code in `checkOverloads`.

2022-03-18 18:19 UTC, bradzacher requested changes
this is looking good to me so far!
I didn't see any test cases for it - could you please add a negative test with the option `false`?

2022-03-18 18:19 UTC, bradzacher commented on packages/eslint-plugin/src/rules/unified-signatures.ts
> +          const signature1 = (b as MethodDefinition).value || b;
```suggestion
          const signature0 = (a as MethodDefinition).value ?? a;
          const signature1 = (b as MethodDefinition).value ?? b;
```

2022-04-08 17:19 UTC, JoshuaKGoldberg commented
Heh, turns out the rule already wasn't testing one of the positive test cases. Classic.

2022-04-08 23:34 UTC, bradzacher approved these changes
LGTM! Thanks for adding this!

2022-04-08 23:34 UTC, bradzacher commented on packages/eslint-plugin/src/rules/unified-signatures.ts
> +    default:
quick note that these is valid:
```ts
function foo({a}: {a: string}): void;
function foo([a]: [a: string]): void;
```

I think it's fine for us to ignore these cases as they're rare and pretty dumb.

2022-04-08 23:34 UTC, merged