Parenthesise conditional types
typescript-eslint/typescript-eslint pull request #4720
Opened 2022-03-23 10:45 UTC by john-h-k

Conditional types aren't handled in the `array-type` rule when converting from generic syntax to array syntax

```tsx
type ClearError<T, U, V> = {
    values: ReadonlyArray<T extends string ? U : V>
    // GOES TO
    values: readonly T extends string ? U : V[] // ERRORS: Parsed as '(readonly T) extends ...` and so is invalid
}

type HiddenError<T, U, V> = {
    values: ReadonlyArray<[T] extends [string] ? U : V
    // GOES TO
    values: readonly [T] extends [string] ? U : V[] // VALID, changes types below
}

type Bar = HiddenError<number, "extends string", "does not extend string">
// BEFORE FIX - Bar = "does not extend string"
// AFTER FIX - Bar = "does not extend string"[]

type Baz = HiddenError<string, "extends string", "does not extend string">
// BEFORE FIX - Bar = "extends string"
// AFTER FIX - Bar = "does not extend string"[]
```

Conditional types being parenthesised resolves this issue

## PR Checklist

-   [ ] Addresses an existing issue: fixes #000
-   [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [ ] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

2022-03-27 03:53 UTC, JoshuaKGoldberg requested changes
Hi, thanks for sending a PR @john-h-k! The code change seems reasonable but isn't unit tested. Could you please add cases in `array-type.test.ts` that exercise the cases shown in the PR description?

We also normally ask that PRs address an open, accepted issue per the pull request template file not filled out here. If it ends up being a longer discussion I'd ask that you do that. Since this fix seems straightforward I think it's fine in the meantime.

2022-03-28 22:53 UTC, bradzacher requested changes
Instead of just adding another item here - we should just fix this up so that it uses TS's actual precedences instead of some hacked together system.

Doing so would also fix #4756

For example, we have achieved this in the general case for binary operators by cloning code from TS itself.
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/util/getOperatorPrecedence.ts

We can do the same here - find the code within TS which specifies the type precedence, and then make an internal utility around it that we can use.

2022-07-23 15:14 UTC, JoshuaKGoldberg commented
👋 @john-h-k just checking in, is this PR still something you have time to work on?

No worries if not - just want to make sure the issue isn't being blocked!

2022-08-17 18:04 UTC, JoshuaKGoldberg commented
I'm going to go ahead and close this PR as it's been open for a long while without activity. 

cc @john-h-k - thanks for working on it!

2022-08-17 18:04 UTC, closed without merging