fix(eslint-plugin): [space-infix-ops] missing error report for conditional types
typescript-eslint/typescript-eslint pull request #5041
Opened 2022-05-22 22:44 UTC by holazz

## PR Checklist

-   [x] Addresses an existing open issue: fixes #5033
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

2022-05-23 06:01 UTC, bradzacher requested changes
We've found reusing selectors like this is very brittle and can easily break!

Instead of hacking the AST to reuse their internal code - let's just fork their logic - it'll be less lines and it'll mean we are better able to modify it in future if we need.

2022-05-23 08:51 UTC, holazz commented
> Thanks for this!
> 
> We've found reusing selectors like this is very brittle and can easily break!
> 
> Instead of hacking the AST to reuse their internal code - let's just fork their logic - it'll be less lines and it'll mean we are better able to modify it in future if we need.

Sorry, I saw some such usage in the source code, I thought it was intentional. I have changed it, please review it.

2022-05-26 11:25 UTC, holazz commented
is there any status update on this? 🤔

2022-05-26 12:21 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
> +        type Test<T> = T extends boolean?true:false
A few edge cases to test for...

* What if there's only a space before, not after? And vice-versa?
* Placing newlines at various points in the ternary, with and without spaces

2022-05-26 12:22 UTC, JoshuaKGoldberg submitted a review, later dismissed
Code looks good, just hoping for some more tests. 🙂

2022-05-26 13:43 UTC, holazz commented
@JoshuaKGoldberg I added some more test cases, please review!

2022-05-26 15:43 UTC, merged