Update README.md
typescript-eslint/typescript-eslint pull request #5277
Opened 2022-06-30 21:03 UTC by Zamiell

- don't use conjunctions
- don't use double-negatives
- clarify what TSLint is

-   [x ] Addresses an existing open issue: fixes #5247

2022-06-30 21:54 UTC, JoshuaKGoldberg requested changes
Thanks for sending this! The latter two changes I agree with and find pleasing. 😄

2022-07-01 00:29 UTC, Zamiell commented on docs/linting/README.md
> +Whether you are adding linting to a new TypeScript codebase, adding TypeScript to an old codebase, or migrating from the deprecated [TSLint](https://www.npmjs.com/package/tslint) tool, the steps to f
In my experience, use of contractions in technical writing is minimized. The benefits of conveying a friendly tone have to be weighed against making the text marginally harder for foreign-language speakers to understand. Here, we expect that people throughout the world will be using the TypeScript programming language, so the documentation should reflect that.

2022-07-01 00:30 UTC, Zamiell commented on docs/linting/README.md
> +Whether you are adding linting to a new TypeScript codebase, adding TypeScript to an old codebase, or migrating from the deprecated [TSLint](https://www.npmjs.com/package/tslint) tool, the steps to f
![image](https://user-images.githubusercontent.com/5511220/176799686-d4a740c2-de11-43f2-9a98-740515090734.png)

2022-07-02 11:54 UTC, Josh-Cena commented on docs/linting/README.md
> +Whether you are adding linting to a new TypeScript codebase, adding TypeScript to an old codebase, or migrating from the deprecated [TSLint](https://www.npmjs.com/package/tslint) tool, the steps to f
"'re" won't be confused with anything; the TS-ESLint docs aren't formal writing either. I do prefer no-contractions myself, but I can't find a reason strong enough to warrant a change, particularly if it sets a precedent.

2022-07-22 15:43 UTC, JoshuaKGoldberg requested changes
Coming back to this PR: the discussion is interesting but the sentence in question is removed by #5248. Once #5248 goes in we can close this PR.

2022-07-23 15:11 UTC, JoshuaKGoldberg commented
Pardon my closing the PR - since #5248 is in, this PR is against deleted code. Thanks though! ❤️

2022-07-23 15:11 UTC, closed without merging