fix(eslint-plugin): no-non-null-asserted-optional-chain infinite loop problem
typescript-eslint/typescript-eslint pull request #5367
Opened 2022-07-24 15:15 UTC by YeeJone

## PR Checklist

-   [x] Addresses an existing open issue: fixes #2521
-   [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Prior to typescript 3.9, the code in the no-non-null-asserted-optional-chain rule had an infinite loop.
Causes the ESLint process to fail to end
```js
while (current) {
    switch (current.type) {
            case AST_NODE_TYPES.MemberExpression:
              if (current.optional) {
                // found an optional chain! stop traversing
                break;
              }

              current = current.object;
              continue;

            case AST_NODE_TYPES.CallExpression:
              if (current.optional) {
                // found an optional chain! stop traversing
                break;
              }

              current = current.callee;
              continue;

            default:
              // something that's not a ChainElement, which means this is not an optional chain we want to check
              return;
      }
}
```

2022-07-29 04:07 UTC, JoshuaKGoldberg commented
In an ideal world, this PR would be blocked on #1752, since it adds a couple of logic branches that aren't tested right now. But getting multi-TS-version testing support is going to be pretty tricky. 🤔

2022-07-31 05:02 UTC, YeeJone commented
> In an ideal world, this PR would be blocked on #1752, since it adds a couple of logic branches that aren't tested right now. But getting multi-TS-version testing support is going to be pretty tricky. 🤔

Indeed, adding multi-TS-version testing capabilities is tricky
Now I don't know how to add unit tests to validate my code...

But this is an obvious problem🐛, and I did some case verification locally with a lower version of TS, and it's fine

2022-07-31 05:06 UTC, YeeJone commented
Now I use this package in a project with a low version of TS, and it often gets stuck, which is too uncomfortable😣

2022-08-17 12:18 UTC, bradzacher requested changes
this code seems like it's pretty wrong anyways - I don't quite know how (or even if) it ever actually worked to begin with.
the intention is that the `break` applies to the outer `while`, but instead it's applying to the `switch`.

The code should instead be like this to explicitly exit the loop.

```ts
const hasOptionalChain = (() => {
  let current = child;
  while (current) {
    switch (current.type) {
      case AST_NODE_TYPES.MemberExpression:
        if (current.optional) {
          // found an optional chain! stop traversing
          return true;
        }

        current = current.object;
        continue;

      case AST_NODE_TYPES.CallExpression:
        if (current.optional) {
          // found an optional chain! stop traversing
          return true;
        }

        current = current.callee;
        continue;

      default:
        // something that's not a ChainElement, which means this is not an optional chain we want to check
        return false;
    }
  }
})();

if (!hasOptionalChain) {
  return;
}
```

this is much clearer than the existing code and it explicitly breaks from the loop rather than implicitly exiting

2022-08-19 02:08 UTC, YeeJone commented
> explicitly

It has been modified, please help to review the code

2022-10-26 20:10 UTC, JoshuaKGoldberg requested changes
Could you add some unit tests verifying the behavior please? There are a lot of "line ... was not covered by tests" comments, which are indicating we can't be sure in CI this won't break in the future.

2022-11-16 16:48 UTC, closed without merging