tests: add dependency constraints to eslint-plugin tests
typescript-eslint/typescript-eslint pull request #5916
Opened 2022-11-02 06:32 UTC by bradzacher

## PR Checklist

- [x] Addresses an existing open issue: ref #1752
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

Doing this ahead of #5573 to improve reviewability.
This PR marks all of our dependency requirements for tests back to TSv4.0.8 - I didn't go back further because #5915 bumps the minimum past that anyways

2022-11-13 23:30 UTC, JoshuaKGoldberg submitted a review, later dismissed
🔥

2022-11-13 23:30 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
> +ruleTesterWithNoUncheckedIndexAccess.run('', rule, {
```suggestion
ruleTesterWithNoUncheckedIndexAccess.run('non-nullable-type-assertion-style', rule, {
```

2022-11-13 23:30 UTC, JoshuaKGoldberg submitted a review, later dismissed

2022-11-13 23:33 UTC, JoshuaKGoldberg submitted a review, later dismissed

2022-11-14 01:02 UTC, JoshuaKGoldberg commented
I see some new test failures after my merge - will try to fix soon...

2022-11-15 14:28 UTC, JoshuaKGoldberg commented
@bradzacher `non-nullable-type-assertion-style` has a failure - otherwise this looks good to go!

2022-11-15 14:29 UTC, JoshuaKGoldberg requested changes
`non-nullable-type-assertion-style` has a failure - otherwise this looks good to go!

2022-11-16 08:06 UTC, bradzacher commented
Interestingly the changes to that failing test have exposed a bug in our underlying project caching logic!
Fix is in #5999

2022-11-16 14:06 UTC, JoshuaKGoldberg approved these changes
🔥

2022-11-17 00:03 UTC, merged