fix/issue5991-fix-prefer-optional-chain-BinaryExpression-in-negated-or
typescript-eslint/typescript-eslint pull request #5992
Opened 2022-11-15 13:19 UTC by omril1

## PR Checklist

- [x] Addresses an existing open issue: fixes #5991
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

2022-11-15 15:22 UTC, JoshuaKGoldberg requested changes
Looks great in general, thanks for sending this in so quickly! Just requesting changes for a little code simplification please. 🎉

2022-11-15 15:22 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/prefer-optional-chain.ts
> +            break;
There's already a `case` a few lines above for `AST_NODE_TYPES.Literal` and `AST_NODE_TYPES.TemplateLiteral`. Could you add this there please?

2022-11-16 01:50 UTC, merged

2022-11-17 08:41 UTC, RobYed commented
@omril1 Thanks for the quick fix!

@JoshuaKGoldberg Do you have an estimate of when this fix will be released? My project is also affected by this issue, thus looking forward to the next release.

2022-11-17 10:24 UTC, bradzacher commented
@RobYed https://github.com/typescript-eslint/typescript-eslint/blob/main/README.md#versioning

2022-11-17 16:26 UTC, RobYed commented
@bradzacher Thanks! I must have been blind! 🙈