avoid unnecessary calls to getContextualType
typescript-eslint/typescript-eslint pull request #6193
Opened 2022-12-09 20:50 UTC by scottarver

## PR Checklist

- [x] Addresses an existing open issue: fixes #6186
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

It appears that `returnsThenable` is faster than `getContextualType` in almost all cases. 
This PR only calls `getContextualType` when needed, after `returnsThenable` returns true.

I ran numbers on how often this is the case: Out of 19,425 total checks, only 96 (33+63) needed a call to  `getContextualType`, this saved 19329 (17289 + 2040 )  calls to `getContextualType` by short circuiting with `returnsThenable`
Also of note on average, `returnsThenable` took 0.12891074558698418ms to run vs `getContextualType` taking 0.5058407855855643ms, saving 9.8 seconds. 
```
total time saved:  9817.560766001232
{
  thenableAndContextual: 33,
  NotThenableAndContextual: 17289,
  thenableAndNotContextual: 63,
  NotThenableAndNotContextual: 2040
}
thenable count:  19425
thenable average: 0.12891074558698418
contextualType count:  19425
contextualType average: 0.5058407855855643
```

Using the chrome profiler to compare:  ran with `node --inspect-brk ./node_modules/.bin/eslint src`
Each check* fn has to be looked at together as a whole, in the table below on a single run it saved 1.2 seconds
| Before | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/6730885/206792990-7bb4fa99-ce75-478a-b482-71e0594a0c9c.png) | ![image](https://user-images.githubusercontent.com/6730885/206793033-d29a014c-ac76-477f-90d4-d162b25e5016.png) |

  | before | after |   |   |  
-- | -- | -- | -- | -- | --
checkTestConditional | 73.6 | 77 |   |   |  
checkConditional | 2.4 | 3.6 |   |   |  
checkAssignment | 1.7 | 2.9 |   |   |  
checkVariableDeclaration | 1160.5 | 1207.4 |   |   |  
checkProperty | 74.4 | 40.2 |   |   |  
checkReturnStatement | 9.2 | 56.1 |   |   |  
checkJSXAttribute | 2076.9 | 754.7 |   |   |  
checkArguments | 121.6 | 125.6 |   |   |  
checkSpread | 5.5 | 4.4 |   | ms diff | seconds
  | 3525.8 | 2271.9 |   | 1253.9 | 1.2539

2022-12-12 20:33 UTC, JoshuaKGoldberg requested changes
This started out as a nice performance improvement - and now is also an unnecessary code removal and/or test expansion opportunity! Great either way 😄

2022-12-12 20:33 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-misused-promises.ts
> +          return;
> Added line #L291 was not covered by tests

If these lines aren't getting hit by tests, then one of two things is possible:

* These lines are unhittable and can be removed
* The tests are missing cases that your code does hit

Do you have examples of the latter? If not, I'd assume it's the former and we can remove the lines.

2023-02-05 01:55 UTC, JoshuaKGoldberg commented
👋 ping @scottarver - is this still something you have time for? No worries if not, just checking in.

2023-03-13 16:17 UTC, JoshuaKGoldberg commented
Ooh, I removed some more calls and all of the unit tests are failing... but now we've got lint failures in the project itself. So we've got to add unit tests! 🙌 

https://cloud.nx.app/runs/NHi3D9Xh0H

```plaintext
/home/runner/work/typescript-eslint/typescript-eslint/packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
  172:18  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  173:16  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  174:22  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  175:22  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  176:24  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises
  177:23  error  Promise-returning function provided to property where a void return was expected  @typescript-eslint/no-misused-promises

/home/runner/work/typescript-eslint/typescript-eslint/packages/eslint-plugin/src/rules/ban-types.ts
  203:41  error  Promise-returning function provided to variable where a void return was expected  @typescript-eslint/no-misused-promises

/home/runner/work/typescript-eslint/typescript-eslint/packages/eslint-plugin/src/rules/block-spacing.ts
...
```

2023-03-13 21:08 UTC, merged

2023-03-13 21:29 UTC, jakebailey commented
Truthfully I didn't even realize these APIs were available, let alone useful externally. Clearly, I'm wrong.

I think someone more experienced than me will have to write out explanations of those. I'll file an issue to track this request; meant to do that post-meeting but forgot.