fix(typescript-estree): account for nested namespace nesting in AST conversion
typescript-eslint/typescript-eslint pull request #6272
Opened 2022-12-24 04:56 UTC by JoshuaKGoldberg

## PR Checklist

- [x] Addresses an existing open issue: fixes #4966
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken

## Overview

TypeScript produces a nested body AST for Identifier names like `abc.def`. This unravels their body blocks and accumulates the name if necessary.

2022-12-24 05:16 UTC, JoshuaKGoldberg commented on packages/typescript-estree/src/convert.ts
> +      name = `${name}.${node.name.text}`;
#6116 🤷

2022-12-24 05:16 UTC, JoshuaKGoldberg commented on packages/typescript-estree/src/convert.ts
> +    result.loc ??= getLocFor(result.range[0], result.range[1], this.ast);
Couldn't resist while I was here 😄 

Feels like this should be a lint rule enabled always...

2023-01-30 07:43 UTC, bradzacher requested changes
I do wish we could use `Identifier` for the dotted name - unfortunately `Identifier.name` needs to be a valid JS identifier - dots aren't allowed!

Instead we can convert this to a `TSQualifiedName`

2023-02-13 03:56 UTC, bradzacher commented
Now that #6443 has landed in main, we'll need to merge v6 then update this PR accordingly.

2023-02-20 22:42 UTC, bradzacher approved these changes
![all_green](https://user-images.githubusercontent.com/7462525/220208545-29aa51fc-f3f8-46f5-a218-1eb675b947a8.gif)

2023-02-21 03:40 UTC, merged