Fix/issue 6439
typescript-eslint/typescript-eslint pull request #6724
Opened 2023-03-21 07:26 UTC by Solo-steven

## PR Checklist

- [x] Addresses an existing open issue: fixes #6439 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

fix issue #6439

2023-03-21 08:52 UTC, bradzacher requested changes
I guess the question here is whether or not an explicit `null` should be ignored like this and overridden by the default, or if it should be seen as a value that shouldn't be overridden.

I think an explicit `null` should not be overridden, personally.

2023-03-21 09:13 UTC, Solo-steven commented
@bradzacher  Thanks for your reply, I think another solution is adding one more conditional to `isObjectNotArray` like
```ts
function isObjectNotArray<T extends ObjectLike>(
  obj: unknown | unknown[],
): obj is T {
  return typeof obj === 'object' && obj != null && !Array.isArray(obj);
}
```
this solution wouldn't overwrite the null value .

But I want to know why we shouldn't overwrite the value, is it cause more errors?

2023-03-21 09:16 UTC, bradzacher commented
> But I want to know why we shouldn't overwrite the value, is it cause more errors?

If a user does a config like `{ foo: null }`, and the default is `{ foo: { bar: '' } }`, then we should not override the explicit `null` with `{ bar: '' }`.
The same can be said for a top-level `null`. If the user configures a rule like `['error', null]`, then we should not override that explicit `null` with whatever the default is.

Instead I think that we should only override `undefined`, as we currently do for non-top-level values.

2023-03-21 20:10 UTC, JoshuaKGoldberg approved these changes
Nice, thanks for this!

2023-03-21 20:10 UTC, JoshuaKGoldberg commented on packages/utils/src/eslint-utils/applyDefault.ts
> -
[Nitpick] Unrelated change, let's take it out. No need to increase the diff size.

2023-07-16 23:46 UTC, JoshuaKGoldberg commented
👋 @bradzacher I think this got dropped from the queue because I did a silly. Do you want to review this one?

It looks good to me, but just making sure.

2023-07-16 23:46 UTC, JoshuaKGoldberg submitted a review, later dismissed
💯 Thanks! And, sorry for the long wait!

2023-07-17 01:02 UTC, bradzacher approved these changes

2023-07-17 01:56 UTC, merged