feat(plugin-test-formatting): noUnnecessaryNoFormat
typescript-eslint/typescript-eslint pull request #6853
Opened 2023-04-06 10:05 UTC by Jolg42

## PR Checklist

- [x] Addresses an existing open issue: fixes #6128
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

I followed the proposal in https://github.com/typescript-eslint/typescript-eslint/issues/6128 and added a check for unnecessary `NoFormat` occurrences, with a test.

2023-04-06 22:40 UTC, JoshuaKGoldberg requested changes
Functionality looks great, thanks for sending this @Jolg42! Requesting changes on the internals, but if you hate what I'm suggested we can certainly ignore me. 😄

2023-04-06 22:40 UTC, JoshuaKGoldberg commented on packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
> +      silent?: boolean,
[Refactor] Hmm, I'm not generally a fan of adding boolean parameters to modify core behavior of a function. It makes it hard to keep track of the function's responsibilities & adds to its complexity. I think the code would be easier to wrangle if we extract out the logic we actually care about from the existing function into a new one.

How about this  of function signatures?

* `function getCodeFormatted(code: string): string | FormattingError | null`
* `function getCodeFormattedOrReport(code: string, location: TSESTree.Node): string | null`

...where `FormattingError` indicates the error message, `getCodeFormatted` contains the call to Prettier, and `getCodeFormattedOrReport` contains the call to `context.report`?

2023-04-06 22:40 UTC, JoshuaKGoldberg commented on packages/eslint-plugin-internal/tests/rules/plugin-test-formatting.test.ts
> +    // empty lines are valid when everything else is indented
[Praise] 😄 nice spot

2023-07-17 00:04 UTC, JoshuaKGoldberg commented
👋 @Jolg42 just checking in, did you want to re-request our review on this one? And/or, is this still something you have time to work on?

No worries if not, I just don't want to leave it dangling. And it is a very lovely change 😄

2023-07-30 06:33 UTC, Jolg42 commented
@JoshuaKGoldberg Thanks for checking-in and I'm sorry for not answering earlier, I still have to work on this 😅

2023-07-31 02:47 UTC, JoshuaKGoldberg commented
No worries! Next time I'm in Berlin, we can always pair on it. 😄

2023-10-17 19:27 UTC, JoshuaKGoldberg commented
Closing this PR as it's been stale for a few months without activity. Feel free to reopen @Jolg42 if you have time - but no worries if not! If anybody wants to drive it forward, please do post your own PR - and if you use this as a start, consider adding `Co-authored-by: @Jolg42` at the end of your PR description. Thanks! 😊

2023-10-17 19:27 UTC, closed without merging