fix(type-utils): treat custom type roots as external
typescript-eslint/typescript-eslint pull request #6870
Opened 2023-04-08 11:56 UTC by RebeccaStevens

## PR Checklist

- [x] Addresses an existing open issue: fixes #6868
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

2023-04-08 11:57 UTC, RebeccaStevens commented
@marekdedic

2023-04-08 12:06 UTC, marekdedic commented
Oh, great! I was going to write in #6866 that I'd like to port that logic to `PackageSpecifier` :D

BTW, there'll be a merge conflict with #6780, but no big deal, they're both tiny changes...

2023-04-08 12:09 UTC, marekdedic commented
Adding a test for this would probably be quite convoluted, right?

2023-04-16 20:01 UTC, JoshuaKGoldberg requested changes
Yip, similar to the other one, seems reasonable but let's test 👍

2023-06-17 18:03 UTC, marekdedic reviewed
I think this is mixing #6861 and #6868 together - I don't know if that's a good thing, a bad thing, or neither :D

2023-07-07 15:17 UTC, JoshuaKGoldberg commented on packages/type-utils/typings/typescript.d.ts
> +
Yeah for now I think it's fine. If they change that API we should see breakages in the TS version upgrade PR.

2023-07-07 15:26 UTC, JoshuaKGoldberg commented on packages/type-utils/src/TypeOrValueSpecifier.ts
> +  return name.some(item => item === (symbol.escapedName as string));
```diff
<<<<<<< HEAD
  return name.some(item => item === (symbol.escapedName as string));
=======
  return name.some(item => (item as ts.__String) === symbol.escapedName);
>>>>>>> v6
```

lol

2023-07-07 16:05 UTC, JoshuaKGoldberg commented
@RebeccaStevens I'm hoping to get through the last bits of v6 work today since we're set to launch on Monday. I think that'll just entail merging `v6` into this PR's branch and adding a few unit tests - which I'm fine to do on my own, and plan on doing in a few hours. Please let me know if you already started and I can hold off 😄

2023-07-08 00:40 UTC, JoshuaKGoldberg commented
Hmm, yeah, these unit tests are tough. I ran out of time tonight. Will try again tomorrow.

2023-07-08 21:46 UTC, JoshuaKGoldberg commented
😕 I can't figure this out. https://github.com/typescript-eslint/typescript-eslint/commit/43d9d753353fa4342985d459f9a3894c0f153c77 shows a unit test that I would think should populate `program.sourceFileToPackageName`, but it's _`Map(0) {size: 0}`_. Either I've misunderstood how to use the combination of `typeRoots` + `sourceFileToPackageName` _(more likely)_, or that currently-internal API isn't made for this use case _(also plausible)_, or there's a bug with `sourceFileToPackageName` _(less likely)_.

2023-07-08 21:56 UTC, JoshuaKGoldberg commented
😕 I can't figure this out. https://github.com/typescript-eslint/typescript-eslint/commit/9b4948056790f764b3864badc57823db82cc528e shows a unit test that I would think should populate `program.sourceFileToPackageName`, but it's _`Map(0) {size: 0}`_. Either I've misunderstood how to use the combination of `typeRoots` + `sourceFileToPackageName` in this unit test _(more likely)_, or that currently-internal API isn't made for this use case _(also plausible)_, or there's a bug with `sourceFileToPackageName` _(less likely)_.

To repro:

1. Put a breakpoint on https://github.com/JoshuaKGoldberg/typescript-eslint/blob/9b4948056790f764b3864badc57823db82cc528e/packages/type-utils/src/TypeOrValueSpecifier.ts#L166
2. Open `TypeOrValueSpecifier.test.ts`
3. Launch the VS Code debugger for _Run currently open type-utils test_ (<kbd>F5</kbd>)
4. Observe that `program.sourceFileToPackageName` is empty, even though earlier in the call stack (https://github.com/JoshuaKGoldberg/typescript-eslint/blob/959819186291a93e17e99e52973a68f3a352c2f5/packages/type-utils/tests/TypeOrValueSpecifier.test.ts#L146), `type` is correctly resolved to `export interface Foo`

2023-07-09 03:00 UTC, RebeccaStevens commented
Yeah, I gave up on the test too. I came to the conclusion that internal test API thingy isn't setup to do these sort of tests. I didn't want to open that can of worms of editing that.

If I remember right, local tests I tried using a separate repo passed. I can't really turn those into unit test though.

2023-07-10 19:32 UTC, JoshuaKGoldberg commented
This was unintentionally auto-closed when we merged the `v6` branch 🙃 it'll be recreated.

2023-10-17 19:17 UTC, JoshuaKGoldberg approved these changes
Yeah, this is a tricky one. All the existing unit tests still pass, and I couldn't figure out how to add unit tests for the new behavior. It's been sitting for a while... let's ship it. 🤘

Sorry for taking so long!

<img alt="Cartoon animation of a ship on water" src="https://media1.giphy.com/media/l0MYSryDg63YEmXVS/giphy.gif"/>

2023-10-17 19:36 UTC, merged