WIP: blog post on parserOptions.project = true
typescript-eslint/typescript-eslint pull request #7368
Opened 2023-07-28 20:21 UTC by JoshuaKGoldberg

## PR Checklist

- [x] Addresses an existing open issue: fixes #6520
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Throwing this up now to make it easier to find my branch later & work across computers...

References:

* https://github.com/typescript-eslint/typescript-eslint/issues/101
* https://github.com/typescript-eslint/typescript-eslint/pull/6084

2023-09-07 23:54 UTC, bradzacher submitted a review, later dismissed

2023-09-08 03:05 UTC, Josh-Cena requested changes
Some nits

2023-09-08 03:05 UTC, Josh-Cena commented on packages/website/blog/2023-08-02-parser-options-project-true.md
> +Each TSConfig file on disk is generally used to create exactly one Program, so files that refer to the same TSConfig file will reuse the same Program.
```suggestion
Each TSConfig file on disk is generally used to create exactly one Program, and files included by the same TSConfig file will reuse the same Program.
```

2023-09-08 03:05 UTC, Josh-Cena commented on packages/website/blog/2023-08-02-parser-options-project-true.md
> +- For a single string (e.g. `"tsconfig.json"`), then only one Program will be created, and all linted files will reuse it.
```suggestion
- For a single path (e.g. `"tsconfig.json"`), only one Program will be created, and all linted files will reuse it.
```

2023-09-08 03:05 UTC, Josh-Cena commented on packages/website/blog/2023-08-02-parser-options-project-true.md
> +- For globs and/or arrays (e.g. `"./packages/*/tsconfig.json"`), then each linted file will reuse a Program based on the _first_ matched TSConfig file.
```suggestion
- For globs and/or arrays (e.g. `"./packages/*/tsconfig.json"`), each linted file will use the Program created by the _first_ matched TSConfig file.
```

2023-09-08 03:05 UTC, Josh-Cena commented on packages/website/blog/2023-08-02-parser-options-project-true.md
> +We're hopeful this option will eventually become the standard way to enable typed linting.
```suggestion
We hope this option will eventually become the standard way to enable typed linting.
```

2023-09-08 03:05 UTC, Josh-Cena commented on packages/website/blog/2023-08-02-parser-options-project-true.md
> +If you enjoyed this blog post and/or or use typescript-eslint, please consider [supporting us on Open Collective](https://opencollective.com/typescript-eslint).
```suggestion
If you enjoyed this blog post and/or use typescript-eslint, please consider [supporting us on Open Collective](https://opencollective.com/typescript-eslint).
```

2023-09-08 11:56 UTC, JoshuaKGoldberg commented on packages/website/blog/2023-08-02-parser-options-project-true.md
> +- Using different TSConfigs than what your editor users can result in different lint reports in the editor verses on the command-line
Yeah if you run `eslint --config eslint.some.other.config.js` then you can give it totally different config values than what's in `eslint.config.js`.

2023-09-08 11:57 UTC, JoshuaKGoldberg commented on packages/website/blog/2023-08-02-parser-options-project-true.md
> +Simplifying your configuration now will make it easier to onboard to our new options when they're available.
I believe the current way is correct: one "onboards to" something.

2023-09-08 12:17 UTC, bradzacher submitted a review, later dismissed

2023-09-08 15:08 UTC, Josh-Cena requested changes

2023-09-08 15:08 UTC, Josh-Cena commented on packages/website/blog/2023-08-02-parser-options-project-true.md
> +- Particularly large repos can end up with so many TSConfig globs, they become confusing to developers or even cause [performance issues from overly permissive globs](https://typescript-eslint.io/lin
```suggestion
- Particularly large repos can end up with so many TSConfig globs, they become confusing to developers or even cause [performance issues from overly permissive globs](/linting/troubleshooting/performance-troubleshooting#wide-includes-in-your-eslint-options)
```

2023-09-08 15:08 UTC, Josh-Cena commented on packages/website/blog/2023-08-02-parser-options-project-true.md
> +  - Most commonly, `.eslintrc.(c)js` files can be tricky to lint, resulting in the dreaded [_TSConfig does not include this file_ error](/troubleshooting#i-get-errors-telling-me-eslint-was-configured
```suggestion
  - Most commonly, `.eslintrc.(c)js` files can be tricky to lint, resulting in the dreaded [_TSConfig does not include this file_ error](/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file).
```

2023-09-12 03:30 UTC, Josh-Cena approved these changes
LGTM

2023-09-12 15:22 UTC, armano2 commented on packages/website/blog/2023-09-12-parser-options-project-true.md
> +As of typescript-eslint@5.52.0, we now support providing `true` for `parserOptions.project`:
`typescript-eslint@5.52.0` is marked as email

2023-09-12 15:23 UTC, armano2 commented on packages/website/blog/2023-09-12-parser-options-project-true.md
> +When [`parserOptions.project`](https://typescript-eslint.io/packages/parser#project) is specified, it additionally sets up TypeScript programs that can be used by [typed rules](https://typescript-esl
```suggestion
When [`parserOptions.project`](/packages/parser#project) is specified, it additionally sets up TypeScript programs that can be used by [typed rules](/developers/custom-rules#typed-rules).
```

2023-09-16 21:32 UTC, merged