resolve #7582
typescript-eslint/typescript-eslint pull request #7590
Opened 2023-09-02 06:07 UTC by girishsontakke

## PR Checklist

- [x] Addresses an existing open issue: fixes #7582 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
this PR resolves the issue #7582.

- TS error 2360 was not available in the list of errors at https://github.com/microsoft/TypeScript/blob/v5.2.2/src/compiler/diagnosticMessages.json.
- When trying to negating the left hand operand of [in operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in) in this [typescript playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBCBGArGBeGBvAUJgvtglgGYAUAhAEQDWApgJ7kz5hxICUG2OQA) I was getting TS error with code [2322](https://github.com/microsoft/TypeScript/blob/9684ba6b0d73c37546ada901e5d0a5324de7fc1d/src/compiler/diagnosticMessages.json#L1775);

2023-09-02 09:23 UTC, auvred requested changes
Please update the other codes according to the existing comments on this PR https://github.com/eslint/eslint/pull/17500

---

- https://github.com/typescript-eslint/typescript-eslint/blob/4899b95bf31d42358d95d078e40424ea95934d16/packages/eslint-plugin/src/configs/eslint-recommended.ts#L17

  https://github.com/eslint/eslint/pull/17500#discussion_r1311644449

- https://github.com/typescript-eslint/typescript-eslint/blob/4899b95bf31d42358d95d078e40424ea95934d16/packages/eslint-plugin/src/configs/eslint-recommended.ts#L18

  https://github.com/eslint/eslint/pull/17500#discussion_r1311657506

2023-09-02 09:23 UTC, auvred commented on packages/eslint-plugin/src/configs/eslint-recommended.ts
>          'no-undef': 'off', // ts(2304)
```suggestion
        'no-undef': 'off', // ts(2304) & ts(2552)
```

https://github.com/eslint/eslint/pull/17500#discussion_r1311670674

2023-09-02 09:23 UTC, auvred commented on packages/eslint-plugin/src/configs/eslint-recommended.ts
>          'no-this-before-super': 'off', // ts(2376)
```suggestion
        'no-this-before-super': 'off', // ts(2376) & ts(17009)
```
https://github.com/eslint/eslint/pull/17500#discussion_r1311669537
[playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCbQN4ChkF9WkjAQgI2gFMAPAF0IDsATGeJZaR6AMwHtWAuaCUgJwEsKAcwZNgrCj14BXYKVa8AFAEp6TddFIALfhAB0bVtAC80AORgzojd2kAHQkuXXoGDMixRoAYWBEylDRwCCjq4pJ8svJKvIRgVBIgAJ4s7FxSgkKqoTaaOvqGLuoQ9o4qLm5AA)

2023-09-02 14:24 UTC, JoshuaKGoldberg requested changes
What @auvred said 🙂

2023-09-04 14:17 UTC, girishsontakke commented
Thanks @auvred for the review and the help 🙏. I will add the changes.

2023-09-04 18:23 UTC, auvred approved these changes
Nice! I guess that's it

2023-09-21 13:11 UTC, merged