docs: add in the pull request file to not comment in closed prs
typescript-eslint/typescript-eslint pull request #7592
Opened 2023-09-02 17:27 UTC by sfavello

## PR Checklist

- [x] Addresses an existing open issue: fixes #7586 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Added a part in the pull requests page to not comment in PRs that has been closed and instead to file a new issue.

2023-09-02 18:05 UTC, JoshuaKGoldberg submitted a review, later dismissed
💯 thanks!

2023-09-02 18:05 UTC, JoshuaKGoldberg commented
Oh - looks like a formatting issue in CI? I'm on mobile and can't check deeply at the moment.

2023-09-02 19:47 UTC, sfavello commented on docs/contributing/Pull_Requests.mdx
> +  - Reasoning: It is much easier for maintainers to not lose track of things if they are posted as issues. If you think there’s a bug in typescript-eslint, the right way to ask is to [file a new issu
```suggestion
  - Reasoning: It is much easier for maintainers to not lose track of things if they are posted as issues. If you think there’s a bug in typescript-eslint, the right way to ask is to [file a new issue](https://github.com/typescript-eslint/typescript-eslint/issues/new/choose). The issue templates include helpful & necessary practices such as making sure you're on the latest version of all our packages.
```

2023-09-02 20:00 UTC, sfavello commented
@JoshuaKGoldberg , Sorry about that. There was space after the period. Should be fixed. 👍🏼

2023-09-02 20:07 UTC, JoshuaKGoldberg submitted a review, later dismissed

2023-09-02 20:27 UTC, Josh-Cena requested changes

2023-09-02 20:27 UTC, Josh-Cena commented on docs/contributing/Pull_Requests.mdx
> +- Comment on a closed PRs.
```suggestion
- Comment on a closed PR.
```

2023-09-02 20:27 UTC, Josh-Cena commented on docs/contributing/Pull_Requests.mdx
> +  - Reasoning: It is much easier for maintainers to not lose track of things if they are posted as issues. If you think there’s a bug in typescript-eslint, the right way to ask is to [file a new issu
```suggestion
  - Reasoning: It is much easier for maintainers to not lose track of things if they are posted as issues. If you think there's a bug in typescript-eslint, the right way to ask is to [file a new issue](https://github.com/typescript-eslint/typescript-eslint/issues/new/choose). The issue templates include helpful & necessary practices such as making sure you're on the latest version of all our packages. You can provide the link to the relevant PR to add more context.
```

2023-09-02 21:06 UTC, sfavello commented on docs/contributing/Pull_Requests.mdx
> +  - Reasoning: It is much easier for maintainers to not lose track of things if they are posted as issues. If you think there’s a bug in typescript-eslint, the right way to ask is to [file a new issu
Nice, thank you!

2023-09-05 19:36 UTC, Josh-Cena approved these changes
LGTM

2023-09-05 19:36 UTC, Josh-Cena commented on docs/contributing/Pull_Requests.mdx
> +- Comment on a closed PR.
```suggestion
- Comment on a closed PR
```

2023-09-05 21:09 UTC, JoshuaKGoldberg reviewed
🔥

2023-09-05 21:09 UTC, merged