[prefer-readonly] private fields support
typescript-eslint/typescript-eslint pull request #7686
Opened 2023-09-21 06:20 UTC by Jamesernator

## PR Checklist

- [x] Addresses an existing open issue: fixes #7126
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

This adds private field support to `prefer-readonly` with the same behaviour as for classic TS private properties.

The tests are just duplicates of the existing tests, but with `private name` replaced with `#name`.

2023-09-21 13:15 UTC, JoshuaKGoldberg requested changes
> +5/-1 in implementation
> +907 in tests

Love it 😂. Super thorough tests - nicely done! 👏 

Just requesting changes on a bit of docs too please. Thanks!

2023-09-21 13:15 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/docs/rules/prefer-readonly.md
> +  #neverModifiedPrivateField = 3;
[Docs] Earlier in the page, it says:

> Member variables with the privacy `private` are never permitted to be modified outside of their declaring class. If that class never modifies their value, they may safely be marked as `readonly`.
>
> This rule reports on private members are marked as `readonly` if they're never modified outside of the constructor.

Can you add a mention of `#` privates somewhere in there too? The explanation is no longer accurate now that they're also considered by the rule.

2023-10-18 02:05 UTC, JoshuaKGoldberg commented
👋 Hey @Jamesernator! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging.

2023-10-19 10:31 UTC, Jamesernator commented
> 👋 Hey @Jamesernator! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging.

I've added a small docs change to mention it now affects both typescript `private` modifiers and private fields.

2023-10-19 15:38 UTC, JoshuaKGoldberg approved these changes
Awesome, thanks! The tests are just as awesomely thorough as before. 🚀

2023-10-19 15:38 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/docs/rules/prefer-readonly.md
> +Private member variables (whether using the `private` modifier, or private fields) are never permitted to be modified outside of their declaring class.
[Docs] Just a bit of nitpicking: the `,` is unnecessary I think, and for consistency + clarity it'd be good to show that `#` is the private fields thing.

```suggestion
Private member variables (whether using the `private` modifier or private `#` fields) are never permitted to be modified outside of their declaring class.
```

2023-10-19 18:32 UTC, merged