chore: Add windows ci
typescript-eslint/typescript-eslint pull request #7695
Opened 2023-09-27 05:55 UTC by liuxingbaoyu

## PR Checklist

- [x] Addresses an existing open issue: fixes #6490
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Add windows ci

2023-09-27 18:05 UTC, StyleShit approved these changes
Not a maintainer, but LGTM

2023-09-27 20:18 UTC, JoshuaKGoldberg approved these changes
Am a maintainer and looks good to me! 😄 thanks!

2023-09-27 20:21 UTC, JoshuaKGoldberg commented on .github/workflows/ci.yml
> +        os: [ubuntu-latest, windows-latest]
Actually, hmm... On second thought I'm not confident we really need Windows on both Node 16 and Node 20... my gut is that there won't be any significant changes between the two. And we already have quite a big list of CI checks.

Will wait for another @typescript-eslint/triage-team member to chime in.

2023-10-19 20:34 UTC, JoshuaKGoldberg requested changes
Ok yes sorry for the fake-out @liuxingbaoyu - I don't think we want to run Windows on more than one Node version. In theory there may be changes between them, but in practice I doubt they'll come up enough to justify the extra CI usage.

For context, since my review here we've continuously gone past the allotment for allowed CI jobs in parallel on the GitHub free / open source tier. Having a full extra set of runs for a different Node version would make that situation even worse. 😞 

So, change request: let's just run `windows-latest` on the latest Node version that's also tested in `ubuntu-latest`.

2023-11-13 12:57 UTC, JoshuaKGoldberg commented
👋 Hey @liuxingbaoyu! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging.

2023-11-14 06:18 UTC, liuxingbaoyu commented
Thank you for the reminder! I forgot about it. :)

2023-11-17 18:10 UTC, JoshuaKGoldberg commented
Great! Whenever it's ready for re-review feel free to explicitly re-request mine through GitHub.

2023-11-19 13:34 UTC, JoshuaKGoldberg approved these changes
Great, thanks!

2023-11-19 13:34 UTC, merged

2023-11-20 01:29 UTC, bradzacher commented
This has double the number of CI jobs that gets run for our unit tests (18 -> 36) - which has a BIG impact on our CI queue times and also PR check ready times.

I wonder if we could scope windows to just the latest nodejs version?
Checking 2 node versions on windows is nice, but ultimately isn't going to catch any extra bugs except for some super rare edge-cases.

2023-11-20 02:44 UTC, liuxingbaoyu commented
https://github.com/typescript-eslint/typescript-eslint/pull/7695/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR153-R155

We already do this.🤔

2023-11-20 03:44 UTC, bradzacher commented
Oh sorry - I just saw a massive chunk of jobs spawn off and didn't actually verify things. We run so many I just assumed things incorrectly! My bad.

Oof - I wish there was an easier way to fuzz this so we didn't need so many jobs!