fix(eslint-plugin): [strict-boolean-expression] fix nullable object handling in LogicalExpression
typescript-eslint/typescript-eslint pull request #7895
Opened 2023-11-10 16:42 UTC by barroudjo

## PR Checklist

- [x] Addresses an existing open issue: fixes #7743
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

When a nullable object appears in a logical expression other than nullish coalescing (so `||` or `&&`), the suggested fix could be wrong and introduce a bug (as explained in the [issue](https://github.com/typescript-eslint/typescript-eslint/issues/7743). This MR removes the suggested fix for these cases, and gives a more explicit message.

2023-11-19 14:19 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
> +    node.type === AST_NODE_TYPES.LogicalExpression && node.operator !== '??'
> `&& node.operator !== '??'`

I tried removing this added check locally and no unit tests failed. Either the check is unnecessary or there's a bag in unit test coverage. My hunch is the latter, but haven't looked too deeply. Requesting changes either way.

2023-11-19 14:19 UTC, JoshuaKGoldberg approved these changes
Looks great, very close! Just requesting changes on the lack of coverage. Thanks! ✨ 

Great first contribution 🙂

2023-11-19 14:19 UTC, JoshuaKGoldberg requested changes
_(wrong button first)_

2023-12-29 18:31 UTC, JoshuaKGoldberg commented
👋 Hey @barroudjo! Just checking in, is this still something you have time for? No worries if not - I just don't want to leave it hanging.

2023-12-30 19:04 UTC, barroudjo commented
You're right, I need to get back to it. I should have the time next week.

2024-01-29 16:48 UTC, JoshuaKGoldberg commented
Closing this PR as it's been stale for a while without activity. cc @barroudjo - if you want to keep working on it, that'd be swell. But no worries if you don't have time. If anybody wants to drive it forward, please do post your own PR - and if you use this as a start, consider adding a co-author attribution at the end of your PR description. Thanks! 😊

2024-01-29 16:48 UTC, closed without merging