chore(website): add Deprecating Formatting Rules blog post
typescript-eslint/typescript-eslint pull request #8117
Opened 2023-12-24 05:07 UTC by JoshuaKGoldberg

## PR Checklist

- [x] Addresses an existing open issue: fixes #8115
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Summarizes why we're doing this and links to the ESLint blog post + ESLint Stylistic docs as well.

Also includes a fix to the rule replacements: I'd forgotten `ts/` exists as a separate namespace from `default/`.

2023-12-24 05:08 UTC, JoshuaKGoldberg commented on packages/website/blog/2023-12-25-deprecating-formatting-rules.md
cc @antfu @typescript-eslint/triage-team - I wish I'd thought to write this post alongside #8072/#8073. Ah well. I've set a reminder to merge this PR in on Monday before our scheduled weekly release.

2023-12-24 09:09 UTC, Josh-Cena approved these changes
Content looks great; not sure if the code change should be a separate PR but no strong feelings

2023-12-24 10:13 UTC, auvred requested changes
Nice post!

I just found a few typos

---

By the way, maybe this has already been discussed somewhere, but I missed it:
What about [`no-extra-semi`](https://typescript-eslint.io/rules/no-extra-semi) rule? It's classified as `suggestion` rather than `layout`, but [it's already a part](https://github.com/eslint-stylistic/eslint-stylistic/blob/de02f0008a8293c44f7d77270a927cdfa936ed46/packages/eslint-plugin-ts/rules/index.ts#L41) of `eslint-stylistic`

Shouldn't we deprecate it as well? Because otherwise it will be duplicated in both `ts-eslint` and `eslint-stylistic`

2023-12-24 10:13 UTC, auvred commented on packages/eslint-plugin/src/rules/lines-between-class-members.ts
> +    replacedBy: ['@stylistic/ts/line-between-class-members'],
```suggestion
    replacedBy: ['@stylistic/ts/lines-between-class-members'],
```

2023-12-24 10:15 UTC, Josh-Cena commented
I asked a while ago privately; I think Brad is in favor of removing it too :)

2023-12-24 18:21 UTC, JoshuaKGoldberg commented on packages/website/blog/2023-12-25-deprecating-formatting-rules.md
> +| [`@typescript-eslint/lines-between-class-members`](/rules/lines-between-class-members)        | [`@stylistic/line-between-class-members`](https://eslint.style/rules/ts/between-class-members)
Thanks :)

2023-12-24 18:23 UTC, JoshuaKGoldberg commented
> if the code change should be a separate PR

Heh yeah in theory maybe. But it's all going to ship at the same time.

2023-12-25 02:43 UTC, merged

2023-12-25 13:18 UTC, antfu commented
Thank you! And Merry Christmas to you all!