feat(eslint-plugin): [no-unnecessary-type-assertion] detect unnecessary non-null-assertion on a call expression
typescript-eslint/typescript-eslint pull request #8143
Opened 2023-12-27 10:38 UTC by lvjiaxuan

## PR Checklist

- [x] Addresses an existing open issue: fixes #8141
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

2024-01-11 17:15 UTC, JoshuaKGoldberg requested changes
Good stuff! Looks like it works well, so just requesting changes on test coverage and fixing the internal lint complaint.

Btw this is a bugfix rather than a feature so I've edited the PR title. They show up differently in the changelog and have different semver version bump implications.

![Girl from the Muppet Christmas Carol saying 'wonderful' happily](https://github.com/typescript-eslint/typescript-eslint/assets/3335181/422064c6-19f9-4427-820d-7a4722995671)

2024-01-11 17:15 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
[Cleanup] I can't comment on an unchanged file 😄 but it looks like this bugfix found an unnecessary `!` assertion in `packages/eslint-plugin/src/rules/no-unnecessary-condition.ts`! Great!

We ensure that lint rules pass on our current codebase as a form of testing. So that'll need to be fixed as part of this PR.

2024-01-11 17:15 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
[Testing] Interestingly, the fact that this line in `no-unnecessary-condition.ts` wasn't caught by the rule:

```ts
const callback = node.arguments[0]!;
```

...indicates a gap in code coverage for the rule which this change also fixes. Could you please add test coverage that case too?

2024-01-11 17:15 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
> +              return fixer.removeRange([node.range[1] - 1, node.range[1]]);
[Praise] Nice call for the parenthesis!

2024-01-12 01:31 UTC, lvjiaxuan commented on packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
okay, I will do it later.

2024-01-12 07:40 UTC, JoshuaKGoldberg approved these changes
Swell, thanks! 🙌

2024-01-12 07:40 UTC, merged