docs: blog post for v7
typescript-eslint/typescript-eslint pull request #8400
Opened 2024-02-07 05:57 UTC by bradzacher

## PR Checklist

- [x] Addresses an existing open issue: fixes #8346
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Adds a blog post for the v7 release to summarise the changes and announce our new package.

2024-02-07 06:41 UTC, JamesHenry commented on packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
> +The simplest of this new tooling would be:
Seem to be missing a word here? Simplest usage? Simplest example?

2024-02-07 18:33 UTC, JoshuaKGoldberg requested changes
Looks good as a start! 🚀 

Requesting changes on a bit more info.

2024-02-07 18:33 UTC, JoshuaKGoldberg commented on packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
> +- [The `typescript-eslint` package documentation](/packages/typescript-eslint)
[Aside] Oh, that reminds me: I'd wanted to look at adding more to https://typescript-eslint.io/packages... filed #8403.

2024-02-09 19:55 UTC, JoshuaKGoldberg submitted a review, later dismissed
🚀 Whoohoo!

This looks great, thanks for all the writing-up. I just left some small things inline - nothing blocking IMO.

2024-02-09 19:55 UTC, JoshuaKGoldberg commented on packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
> +The intent behind this release is for us to constrain variance in our dependencies to help set us up for the future. The upcoming ESLint v9 release will contain many API removals - all of which had r
[Proofreading] Nit: using the same sentence structure twice in a row can feel a little repetitive. Somehow avoiding using _"main point - corollary"_ would be good.

I think the second after-the-hyphen doesn't super need to be said in this post, so how about:

```suggestion
The intent behind this release is for us to constrain variance in our dependencies to help set us up for the future. The upcoming ESLint v9 release will contain many API removals - all of which had replacements added in some of the latest ESLint v8 releases. By enforcing that you have the latest ESLint v8 release we ensure that you have the replacement APIs. This significantly reduces our maintenance burden and should mean we can release v9 support sooner and with less pain and effort.
```

2024-02-09 19:55 UTC, JoshuaKGoldberg commented on packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
> +With v7 we're releasing a new package - `typescript-eslint`. This package can be imported within your [flat config](https://eslint.org/docs/latest/use/configure/configuration-files-new) to access our
[Proofreading] Nit: emphasizing a bit more with the bold, and I think a comma is more appropriate?

```suggestion
With v7 we're releasing a new package, **`typescript-eslint`**. This package can be imported within your [flat config](https://eslint.org/docs/latest/use/configure/configuration-files-new) to access our configs, plugin, and parser. This package also exports a utility function called `config` which will allow you to write type-checked configuration files!
```

2024-02-09 19:55 UTC, JoshuaKGoldberg commented on packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
> +
[Proofreading] Thinking on this again, I wonder if folks will worry that they _have_ to use flat config / `typescript-eslint`? Maybe:

```suggestion

You don't have to use this package if you haven't yet migrated to flat configs.
But once you do, this is our recommend way to set up our tooling.

```

2024-02-09 19:55 UTC, JoshuaKGoldberg commented on packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
> +Because this new package includes dependencies on our plugin and parser meaning you can replace those dependencies entirely:
[Typo]

```suggestion
Because this new package includes dependencies on our plugin and parser, you can replace those dependencies entirely:
```

2024-02-09 19:55 UTC, JoshuaKGoldberg commented on packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
> +
[Proofreading] The narrative flow from _"it allows you to ..."_ to _"here's how to set it up"_ was a bit of a jump for me. Maybe putting the two sections in headings would be helpful?

```suggestion

### Switching to `typescript-eslint`

```

...and after the first code block, maybe:

```md
### Using `typescript-eslint`
```

2024-02-09 21:25 UTC, merged

2024-02-15 05:25 UTC, hyunbinseo commented
Regarding the Node.js engine requirements:

> Update Node.js engine requirement to `^18.18.0 || >=20.0.0`. 
> …
> Note that this is the same requirement that ESLint v9 will impose.

https://github.com/typescript-eslint/typescript-eslint/blob/b27de997c87ffd62785acd86269491dd41883ab9/package.json#L52-L54

the ESLint team decided to use `^18.18.0 || ^20.9.0`.

- https://github.com/eslint/eslint/issues/17595
- https://github.com/eslint/eslint/pull/17725

This is because v20 LTS started from `v20.9.0`.

https://nodejs.org/en/blog/release/v20.9.0

Either the blog post or the `package.json` should be updated?

2024-02-15 05:45 UTC, bradzacher commented
Oh looks like I didn't copy past correctly.
Oh well - it's close enough really. If someone's on v20 it should be close to a no-op for them to upgrade to v20.9

With our next major well bump it properly.

2024-02-15 05:59 UTC, hyunbinseo commented
Thanks for the confirmation.

I understand that it is a breaking change, but enforcing v20 LTS in a minor release seems viable.