docs: fix invalid relative link in getting started page details section
typescript-eslint/typescript-eslint pull request #8468
Opened 2024-02-14 10:16 UTC by salitha-pathi

## PR Checklist

- [ ] Addresses an existing open issue
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [ ] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Hey there! 👋

In the previous update to the link in the "Getting Started" page, it was pointing from the current directory, but it actually needed to go one directory up. My apologies for the mistake.

This PR fixes that issue by adjusting the link appropriately.

Thanks for reviewing! 🚀

2024-02-14 14:08 UTC, salitha-pathi commented
> this was already fixed.

still cannot see on the server. going to invalid page

2024-02-14 14:29 UTC, bradzacher commented
@salitha-pathi you'll likely need to force refresh the page.
The page caches things with a service worker for offline use so it can take a few refreshes to update sometimes.

2024-02-14 14:30 UTC, bradzacher commented
Oh wait

2024-02-15 14:50 UTC, auvred requested changes

2024-02-15 14:50 UTC, auvred commented on docs/Getting_Started.mdx
>  - [Plugins](https://eslint.org/docs/latest/use/configure/plugins): set to [`@typescript-eslint/eslint-plugin`](./packages/ESLint_Plugin.mdx) to load [rules listed in our _Rules_ page](./Rules).
```suggestion
- [Plugins](https://eslint.org/docs/latest/use/configure/plugins): set to [`@typescript-eslint/eslint-plugin`](./packages/ESLint_Plugin.mdx) to load [rules listed in our _Rules_ page](/rules).
```

Let's fix one more broken link in this PR? 

https://github.com/typescript-eslint/typescript-eslint/issues/8480

2024-02-16 02:15 UTC, bradzacher approved these changes

2024-02-16 02:31 UTC, merged