docs: describe when to use `evaluating community engagement` and `wontfix` labels in Issue Flow
typescript-eslint/typescript-eslint pull request #8489
Opened 2024-02-16 11:28 UTC by auvred

## PR Checklist

- [x] Addresses an existing open issue: fixes #8435
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Brad wrote a great explanation here - https://github.com/typescript-eslint/typescript-eslint/issues/8435#issuecomment-1940412549! I've tried to keep the same structure and meaning.

2024-02-16 13:02 UTC, JoshuaKGoldberg commented on docs/maintenance/Issues.mdx
> +If this is the case, you should read the original issue to gather context, understand the reason for it being closed, and determine if the new issue raises any new or relevant point that requires add
💯 This is great!

2024-02-16 15:49 UTC, JoshuaKGoldberg requested changes
Looks pretty great to me at first glance, thanks!

A couple of suggestions for clarifying points. Will leave with `1 approval` for a bit to let other team members review too.

2024-02-16 15:49 UTC, JoshuaKGoldberg commented on docs/maintenance/Issues.mdx
> +
This way folks know we're giving them tools to try things out & build community consensus:

```suggestion

For requests that can be implemented outside of typescript-eslint, be sure to mention any relevant APIs such as [Custom Rules](../developers/Custom_Rules.mdx) that can be used.

```

2024-02-16 16:30 UTC, auvred commented on docs/maintenance/Issues.mdx
> +A few month after the issue has been opened with `evaluating community engagement` label, the actual engagement of community is evaluated:
This makes perfect sense, thanks!

2024-02-17 07:52 UTC, bradzacher approved these changes
This is looking good to me! Thanks for encoding my random, addled brain thoughts into a permanent guide to lead everyone astray.

2024-02-17 16:17 UTC, JoshuaKGoldberg submitted a review, later dismissed
Just one typo I only noticed now. But this is great, thanks!

2024-02-17 16:17 UTC, JoshuaKGoldberg commented on docs/maintenance/Issues.mdx
> +   - If issue contains enhancement-like request that is unlikely to be implemented on the typescript-eslint side:
```suggestion
   - If issue contains an enhancement-like request that is unlikely to be implemented on the typescript-eslint side:
```

2024-02-17 16:17 UTC, merged