fix(eslint-plugin): [sort-type-constituents] prevent formatting differences in complex types from affecting sort order
typescript-eslint/typescript-eslint pull request #8656
Opened 2024-03-12 19:27 UTC by ericmatthys

## PR Checklist

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [ ] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Currently, `sort-type-constituents` compares all source text for a given "constituent". This means that whitespace can affect the sort order unexpectedly. Particularly when paired with a formatter like Prettier, the addition or removal of a line break can end up violating this lint rule.

Considering these two examples, the first results in a lint error and the second does not, even though you'd assume they'd be sorted the same.

```tsx
type T = { a: string } & {
  b: string
};
```

```tsx
type T = { a: string } & { b: string };
```

I've tried to address these differences without completely changing how the rule works by determining a separate text value on which the sort operates, and this value has normalization to better ignore formatting differences between constituents.

2024-03-25 16:09 UTC, ericmatthys commented
The rule has since been renamed, but I did find this issue with the old name: https://github.com/typescript-eslint/typescript-eslint/issues/3639

2024-03-25 16:21 UTC, JoshuaKGoldberg commented
Aha, great, thanks for finding that! Re-opening this PR and renaming existing issues under the old name.

That brings up a good point that we should probably always rename old issues when we rename a rule. Linking: #8548

2024-03-28 14:09 UTC, JoshuaKGoldberg commented
Note that we're feature-freezing `sort-type-constituents` and other naming & sorting stylistic rules: #8792. Since this PR was sent before #8792 was filed, we'll still accept it. We'd hate to mark work as accepted, then pull it out from under you after you've done the work. 🙂

2024-03-28 15:34 UTC, ericmatthys commented
👍 I'll take a look at https://eslint-plugin-perfectionist.azat.io/ as well. I'm curious how it handles these cases. I won't be bothered if the PR is rejected either way, so no worries there.

2024-04-23 20:27 UTC, JoshuaKGoldberg requested changes
The approach here seems reasonable to me. But in order to avoid a slew of edge case bugs, it'll need to be more comprehensive in which types it accounts for. Have fun! ✨

2024-04-23 20:27 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/tests/rules/sort-type-constituents.test.ts
[Testing] Could you add in a few quick tests for `//` and `/*` style comments, just to make sure they're factored in appropriately?

2024-04-23 20:27 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/sort-type-constituents.ts
> +    ): string {
[Bug] As convenient as `sourceCode.getText` is, most cases where it's used are susceptible to bugs. Here's an example for type parameters in mapped types:

```ts
type _ = {
  [P in 'a' /* now gets included */ | 'b']: string
}
```

This function will need to account for all the AST types that might have comments / formatting differences, included `TSUnionType`, `TSIntersectionType`, and `TSTypePredicate`.

2024-05-26 11:19 UTC, JoshuaKGoldberg commented
👋 ping @ericmatthys, ust checking in - is this still something you have time for?

2024-05-28 16:41 UTC, JoshuaKGoldberg commented
That makes it easier on our end. Either way, thanks for the work so far! ❤️

2024-05-28 16:41 UTC, closed without merging