docs: add homepage
typescript-eslint/typescript-eslint pull request #8742
Opened 2024-03-21 12:51 UTC by moskalakamil

## Overview

Added homepage to `package.json`.

After the merge, the homepage on [npmjs.org](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin) will be replaced with the official documentation.

<img width="1710" alt="screen_of_npmjs.org" src="https://github.com/typescript-eslint/typescript-eslint/assets/91079590/d8ce3eab-3f09-4131-b229-dfd7e7e63374">

2024-03-24 15:41 UTC, Josh-Cena approved these changes

2024-03-25 16:17 UTC, JoshuaKGoldberg requested changes
I ... don't think that this will change the actual `package.json`s that get published with packages? `@typescript-eslint/eslint-plugin`, for example, comes from `packages/eslint-plugin/package.json`. I believe you'll need to make this change in all those nested `package.json`s instead.

Someone please yell at me if there's actually Nx magic under the hood I don't know of.

2024-03-25 16:17 UTC, JoshuaKGoldberg commented on package.json
> +  "homepage": "https://typescript-eslint.io/",
This is super nitpicky, but - there's no need for the trailing slash 😄. Most existing files don't use it.  

```suggestion
  "homepage": "https://typescript-eslint.io",
```

2024-03-25 18:43 UTC, moskalakamil commented
@JoshuaKGoldberg done

2024-03-25 21:34 UTC, JoshuaKGoldberg approved these changes
LGTM, thanks!

I don't have a personal preference of which ones should point to the root website vs. a `/packages/*`. If anybody else does then I suppose they can request changes. 😄

2024-04-01 15:54 UTC, merged