move inside content
typescript-eslint/typescript-eslint pull request #8750
Opened 2024-03-22 04:19 UTC by abrahamguo

## PR Checklist

- [x] Addresses an existing open issue: fixes #8741
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
`NotFound` => `NotFoundContent`

2024-03-22 05:02 UTC, Josh-Cena submitted a review, later dismissed

2024-03-22 13:48 UTC, JoshuaKGoldberg requested changes
..oh, except for the lint issues:

```plaintext

/home/runner/work/typescript-eslint/typescript-eslint/packages/website/src/theme/NotFound/Content/index.tsx
  2:10  error  'PageMetadata' is defined but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars
  3:8   error  'Layout' is defined but never used. Allowed unused vars must match /^_/u        @typescript-eslint/no-unused-vars
```

Got a moment to fix for them?

2024-03-23 00:35 UTC, armano2 commented
there seem to br also small issue on firefox, this underline image seem to be missaligned
![image](https://github.com/typescript-eslint/typescript-eslint/assets/625469/589da017-a0bb-471d-a92b-03c7c910e4ae)

2024-03-23 17:46 UTC, JoshuaKGoldberg approved these changes
Thanks!

2024-03-23 17:46 UTC, merged