enhancement(ast-spect): remove deprecated type params
typescript-eslint/typescript-eslint pull request #8933
Opened 2024-04-15 23:18 UTC by abrahamguo

## PR Checklist

- [x] Addresses an existing open issue: fixes #8927 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
Remove @deprecated `typeParameters` properties that were deprecated in #6274

2024-04-22 23:56 UTC, JoshuaKGoldberg commented on packages/typescript-estree/tests/lib/convert.test.ts
@abrahamguo it looks like there are some test failures, is that something you need help with?

2024-04-22 23:56 UTC, JoshuaKGoldberg requested changes
(waiting on test failures)

2024-04-23 00:03 UTC, abrahamguo commented on packages/typescript-estree/tests/lib/convert.test.ts
I've been procrastinating investigating this deeply haha. I changed the tests to look at a different deprecated property but I'm unsure why they are now saying that no deprecation warnings were triggered. If you have any hunches, lmk!

2024-04-23 01:55 UTC, abrahamguo commented on packages/typescript-estree/tests/lib/convert.test.ts
Actually, upon further inspection, it looks like the only other usages of `#withDeprecatedAliasGetter` are on `assertions` <=> `attributes`, but they have `suppressWarnings` set  to `true`, so they do not emit warnings. Therefore, the warnings created by `#withDeprecatedAliasGetter` are currently unused. Let me know how you would like to update (or remove) the tests.

2024-04-23 12:22 UTC, abrahamguo commented on packages/typescript-estree/tests/lib/convert.test.ts
For now, I've simply removed the tests relating to printing warnings. Let me know if you'd prefer something different.

2024-04-23 12:24 UTC, abrahamguo commented
FYI: This PR introduces new incorrect lint errors from `eslint-plugin-react/prop-types`, because it appears that `eslint-plugin-react` is reading from `typeParameters`, now removed in this PR.

2024-04-23 16:39 UTC, JoshuaKGoldberg commented on packages/typescript-estree/tests/lib/convert.test.ts
I also just noticed this PR is against the `main` branch, but it should be against `v8`. I merged #8920 into `v8` yesterday that I think adds back in some logging stuff. Can you try switching to the now-deprecated `TSEnumDeclaration` `members`?

If there wasn't any use for the old code paths, I'd say they should just be deleted as dead code. But with #8920 I don't think that's the case here.

2024-04-25 20:03 UTC, JoshuaKGoldberg approved these changes
LGTM, thanks! 🙌 Very excited to see most of our `@deprecated` AST spec properties gone.

Since this touches sensitive code, I'll leave it with `1 approval` for another member of @typescript-eslint/triage-team to take a look. I don't trust myself. 🙂 


![Old timey Smurf cartoon showing a smurf sweeping a floor](https://github.com/typescript-eslint/typescript-eslint/assets/3335181/a67038ca-2dbe-4968-9602-61be2aa393ab)

2024-04-25 20:03 UTC, JoshuaKGoldberg commented on eslint.config.mjs
> +        (2) is unnecessary in TypeScript components */
For (1), if it's a transient problem, we'd want to link to the upstream issue (https://github.com/jsx-eslint/eslint-plugin-react/issues/3602). Vague comments tend to get out of date and don't help new readers understand the issue well.

For (2), yup, that's going to last beyond (1) - so I'd say it makes sense to disable the rule here always anyway.

```suggestion
```

2024-05-24 09:12 UTC, merged