Remove deprecated context helpers
typescript-eslint/typescript-eslint pull request #9000
Opened 2024-04-26 12:10 UTC by abrahamguo

## PR Checklist

- [x] Addresses an existing open issue: fixes #8983
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview
Removes the deprecated context helpers for v8.

2024-04-27 13:43 UTC, auvred requested changes

2024-04-27 13:43 UTC, auvred commented on docs/maintenance/Releases.mdx
Could you please revert these changes in `docs/maintenance/Releases.mdx`? (this is due to conflicts with `v8` I guess)

2024-04-27 14:58 UTC, abrahamguo commented on docs/maintenance/Releases.mdx
Those are simply because `v8` is behind `main` — won't `main` get merged into `v8` periodically, making those commits disappear from this PR?

2024-04-27 15:11 UTC, auvred commented on docs/maintenance/Releases.mdx
The base branch for this PR is `v8`. I think that merging `v8` into this branch instead of `main` should help!

2024-04-30 13:42 UTC, auvred approved these changes
Thanks!

2024-04-30 13:42 UTC, merged