fix(typescript-estree): don't add in-project files to defaultProjectMatchedFiles
typescript-eslint/typescript-eslint pull request #9097
Opened 2024-05-14 15:50 UTC by ehoogeveen-medweb

## PR Checklist

- [x] Addresses an existing open issue: fixes #9032
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Only add path to `defaultProjectMatchedFiles` if `opened.configFileName` is falsy.

The fix itself is pretty trivial and existing tests still pass, but I might need some help with adding a new testcase. I tried adapting the existing testcase at https://github.com/typescript-eslint/typescript-eslint/blob/77fc366aa03f3cee1ebcf91a10dc0be8b669520e/packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts#L122 but only succeeded in making *other* tests fail (maybe I mocked a result and then didn't call the function, I'm not sure).

2024-05-14 16:31 UTC, ehoogeveen-medweb commented
Linting is clean locally. From the log, it looks like `website-eslint:lint` failed with an `AtomicsWaitError`, so I doubt it's me 😄

2024-05-15 16:33 UTC, JoshuaKGoldberg commented on packages/typescript-estree/src/useProgramFromProjectService.ts
> need some help with adding a new testcase

Threading here: @ehoogeveen-medweb thanks for working on this! Can you push up what you have for the tests, even with failures? We can take a look.

2024-05-15 16:34 UTC, JoshuaKGoldberg requested changes
Source code change looks nice and clean! 🙌

2024-05-15 18:31 UTC, ehoogeveen-medweb commented on packages/typescript-estree/src/useProgramFromProjectService.ts
I figured it out - turns out there was a pretty similar test further down that I was able to adapt :)

I've confirmed locally that the added test fails without the fix from the first commit, and now passes.

2024-05-15 19:11 UTC, JoshuaKGoldberg approved these changes
![Dwight from The Office jumping up and fisting up in the air triumphantly](https://github.com/typescript-eslint/typescript-eslint/assets/3335181/ea6bb8cb-ea1b-40e0-a723-e17fd3001e36)

2024-05-15 19:11 UTC, merged

2024-05-17 14:55 UTC, karlhorky commented
@ehoogeveen-medweb @JoshuaKGoldberg Thanks for the PR and merge 🙌 

I'm trying out the v8 alpha releases, and I didn't see this change in the latest v8 alpha [`@typescript-eslint/typescript-estree@8.0.0-alpha.13`](https://www.npmjs.com/package/@typescript-eslint/typescript-estree/v/8.0.0-alpha.13?activeTab=code) - could an alpha be published with this change?

2024-05-19 22:23 UTC, JoshuaKGoldberg commented
We merged the `main` branch into `v8` and now [`8.0.0-alpha.14`](https://www.npmjs.com/package/typescript-eslint/v/8.0.0-alpha.14) should include everything. 👍