feat(rule-tester): Add reimplementation of RuleTester
typescript-eslint/typescript-eslint pull request #9331
Opened 2024-06-11 08:28 UTC by luca-script

## PR Checklist

- [x] Addresses an existing open issue: fixes #9017 
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Adds a new `FlatRuleTester` implementation, which supports flat config and has been completely (from scratch) rewritten in full TypeScript with greater performance and following more modern coding standards (Namely defining your rules as code as opposed to passing a giant JSON-esque array)

Porting should be easy via the `FlatRuleConfig.fromObject` method (Which takes a mostly `RuleTester.run`-compatible object)
And should be more performant (Although I have not checked yet)

**BREAKING CHANGES COMPARED TO `RuleTester`**:
- Uses ESLint's flat config system
- Supports per-extension options
- Requires type-checking
- Does not support modifying parserOptions on a per-case basis (For performance reasons)
- 

## TODO

- Add unit tests
- Maybe make the API callback-based, i.e.
```ts
new FlatRuleTester({...}).rule("my-rule", rule, (def) => {
  def.configuration([], (conf) => {
    conf.valid(`console.log('Example');`);
  }));
});
```
- Make it check TypeScript for errors and report on missing type definitions
- Support auto importing types (as if `/// <reference types="...">`)
- Add website documentation and migration guide
- Implement missing options from RuleTester
- By default, we should use `@typescript-eslint/parser` as the parser
- maybe: Add support for a config file in the project root that defines where the fixtureRoot is (Maybe a subclass or configuration option that automatically does that?)
- maybe: Fix internal ESLint `Linter` types
- maybe: More Jest integrations?
- maybe: Support caching results (Very unlikely to be implemented by me)
- maybe: Support string imports for parsers
- maybe: File-based testing? (Make files in a directory, point the RuleTester at it, and it'll test every single file, would also use comments to describe where errors should occur)
- maybe: Support modifying parserOptions on a per-configuration basis (Would affect performance noticably)
- maybe: Hook filesystem APIs to emulate a project (Should improve compatibility with ESLint plugins which require configuration files or file context)

2024-06-27 12:56 UTC, JoshuaKGoldberg requested changes
❔

2024-06-27 12:56 UTC, JoshuaKGoldberg commented on packages/rule-tester/src/FlatRuleTester.ts
@luca-script sorry, I'm very confused here. As I understood it, the backing ESLint PR https://github.com/eslint/eslint/pull/17922 was mostly just a rename. From its OP:

> #### What changes did you make? (Give an overview)
> 1. Removed `RuleTester`
> 2. Renamed `FlatRuleTester` to `RuleTester`
> 3. Updated `api.js` to export the new `RuleTester`
> 4. Updated `unsupported-api.js` to stop exporting `FlatRuleTester`
> 5. Updated the API docs
> 6. Updated the Migrate to v9 guide
> 7. Updated all rule tests

...and our issue #9017 is just for us to do a similar rename.

Why the reimplementation of `FlatRuleTester`?

2024-06-27 16:18 UTC, bradzacher commented on packages/rule-tester/src/FlatRuleTester.ts
For sure. We don't want a complete reimplementation for scratch because we are looking for feature parity with upstream.

The existing implementation is intended to be as close to the original code as possible (warts and all) to make it easy for us to merge upstream changes back in to our fork.

Not that we need parity because it's intended to be a drop-in replacement - an augmentation of the core rule tester.

I don't much care for their code style either - and I would love to rewrite it from scratch - but that will make maintenance harder in the long run.

2024-07-17 03:07 UTC, JoshuaKGoldberg commented
👋 @luca-script is this still something you have time + energy for?

2024-07-18 11:54 UTC, JoshuaKGoldberg commented
> @JoshuaKGoldberg Is this feature only planned for the next major release?

Yes: it's a breaking change so we can't get it into v7.

2024-07-22 02:15 UTC, JoshuaKGoldberg commented
Closing this PR out as I'm tackling the backing issue with #9603.

@luca-script you did a lot of great work in this PR and I'm sad to see it closed. Same as #9346. Next time, I'd suggest reading the issue carefully & checking with us before you put a lot of effort into a big PR. My advice in general is to ease into a new repository with smaller bugfixes & not-exceptionally-complex feature additions before tackling big issues like these ones. ❤️

2024-07-22 02:15 UTC, closed without merging