fix(eslint-plugin): handle abstract members in `no-extraneous-class` rule
typescript-eslint/typescript-eslint pull request #9367
Opened 2024-06-16 07:21 UTC by yoshi2no

## PR Checklist

- [x] Addresses an existing open issue: fixes #9359
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

**Description**
This PR addresses an issue with the @typescript-eslint/no-extraneous-class rule where abstract fields and methods were not being counted as instance properties. The rule implementation was missing the handling of abstract members, which have different AST nodes compared to their concrete counterparts. This fix ensures that abstract fields and methods are correctly recognized as instance properties.

**Changes**
- Updated the no-extraneous-class rule to account for `TSAbstractMethodDefinition` and `TSAbstractPropertyDefinition` nodes.
- Added tests to cover scenarios with abstract classes containing abstract members.

2024-06-16 16:54 UTC, kirkwaiblinger requested changes
@yoshi2no

Congrats on a great first PR to typescript-eslint!

AFAICT, everything that you have so far is perfect! The changes requested are just for a few finishing touches 🙂 Only blocker for me is the request around testing. 

Thanks!

2024-06-16 16:54 UTC, kirkwaiblinger commented on packages/eslint-plugin/tests/rules/no-extraneous-class.test.ts
(testing) Turns out, this file had zero tests for `abstract` classes or fields, prior to your changes 😞 . So, I'd appreciate if you could help us out by adding a handful more tests around this feature in general 🙏 

```ts
// invalid (with `allowEmpty: false`); ensure that abstract classes without instance properties still flag
abstract class Foo {
}

// invalid; ensure that abstract classes with only static properties still report "only static"
abstract class Foo {
    static /* field or method or whatever */;
}

// valid; just shows that a single abstract property is sufficient to count as a non-extraneous class.
abstract class Foo {
    abstract property: string;
}

// valid; just shows that a single abstract method is sufficient to count as a non-extraneous class.
abstract class Foo {
    abstract method(): string;
}
```

2024-06-16 16:54 UTC, kirkwaiblinger commented on packages/eslint-plugin/src/rules/no-extraneous-class.ts
(docs, optional) I think adding one example to the docs page with an abstract could be helpful. Just a real simple example to show at a glance that a single abstract method or property is considered an instance method/property... What do you think?

2024-06-16 16:57 UTC, kirkwaiblinger commented on packages/eslint-plugin/tests/rules/no-extraneous-class.test.ts
(note that I wrote these out quickly, so feel free to let me know if any of them are wrong or don't make sense 🙂)

2024-06-16 17:02 UTC, Josh-Cena commented
Also, TIL that `static abstract` is not legal. Maybe we should have this as a comment.

2024-06-19 17:08 UTC, yoshi2no commented on packages/eslint-plugin/src/rules/no-extraneous-class.ts
@kirkwaiblinger 

That makes sense! I’ve prepared a simple example to be added below the existing examples.
https://deploy-preview-9367--typescript-eslint.netlify.app/rules/no-extraneous-class#examples

2024-06-19 17:09 UTC, yoshi2no commented on packages/eslint-plugin/tests/rules/no-extraneous-class.test.ts
@kirkwaiblinger 

Absolutely! In addition to the tests you suggested, I’ve also added a case where it should be invalid due to only containing a constructor. I appreciate your kind support! Thank you!

2024-06-19 17:25 UTC, kirkwaiblinger requested changes
Great stuff! Just one nit remaining

2024-06-19 17:25 UTC, kirkwaiblinger commented on packages/eslint-plugin/docs/rules/no-extraneous-class.mdx
> +```ts
nit - please include these in the preceeding tabs, rather than making a new one

2024-06-19 17:27 UTC, kirkwaiblinger commented
FYI - to fix the CI failure, you'll need to update the docs snapshots. See https://typescript-eslint.io/contributing/local-development#rule-development

2024-06-19 18:20 UTC, yoshi2no commented
> FYI - to fix the CI failure, you'll need to update the docs snapshots. See https://typescript-eslint.io/contributing/local-development#rule-development

Oops, I missed that. Thanks!

2024-06-19 18:53 UTC, kirkwaiblinger approved these changes
Great work! 🚀 

<img alt="tusken raider celebrates" src="https://media4.giphy.com/media/3ornjPteRwwUdSWifC/giphy.gif"/>

Marking "1 approval" for now, for another team member to take a pass as well before merging

2024-06-22 17:11 UTC, JoshuaKGoldberg approved these changes
Yay!

2024-06-22 17:11 UTC, merged