feat(eslint-plugin): backport no-unsafe-function type, no-wrapper-object-types from v8 to v7
typescript-eslint/typescript-eslint pull request #9507
Opened 2024-07-06 15:41 UTC by JoshuaKGoldberg

## PR Checklist

- [x] Addresses an existing open issue: fixes #9503; fixes #9505
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Also adds the docs touchup requested by #9503 while I'm in the area.

💖

2024-07-12 06:13 UTC, kirkwaiblinger commented
FYI @JoshuaKGoldberg - I've merged https://github.com/typescript-eslint/typescript-eslint/pull/9363 to v8, so you'll want to update this PR with those changes

2024-07-12 06:14 UTC, kirkwaiblinger requested changes
https://github.com/typescript-eslint/typescript-eslint/pull/9507#issuecomment-2224835625

2024-07-13 17:28 UTC, kirkwaiblinger commented on packages/eslint-plugin/docs/rules/no-wrapper-object-types.mdx
> +- [`no-empty-object-type`](https://v8--typescript-eslint.netlify.app/rules/no-empty-object-type)
Is the v8 link still necessary?
```suggestion
- [`no-empty-object-type`](./no-empty-object-type.mdx)
```

2024-07-13 17:28 UTC, kirkwaiblinger commented on packages/eslint-plugin/docs/rules/no-unsafe-function-type.mdx
> +- typescript-eslint@v8's [`no-empty-object-type`](https://v8--typescript-eslint.netlify.app/rules/no-empty-object-type)
can these also be updated?
```suggestion
- [`no-empty-object-type`](https://v8--typescript-eslint.netlify.app/rules/no-empty-object-type)
```

2024-07-14 13:13 UTC, bradzacher approved these changes

2024-07-14 17:39 UTC, kirkwaiblinger submitted a review, later dismissed

2024-07-17 06:21 UTC, kirkwaiblinger approved these changes

2024-07-17 12:17 UTC, JoshuaKGoldberg commented
Aha! The check from #9243 is saving us on this one.

2024-07-17 15:47 UTC, kirkwaiblinger approved these changes

2024-07-17 15:48 UTC, kirkwaiblinger requested changes
Looks like might need to rerun some test snapshots? Otherwise LGTM

2024-07-18 17:21 UTC, kirkwaiblinger approved these changes
🚀

2024-07-18 17:36 UTC, merged