bug(eslint-plugin): delete [] in meesage if ReadOnly<string[]> is detected
typescript-eslint/typescript-eslint pull request #9513
Opened 2024-07-07 21:23 UTC by YutongZhuu

## PR Checklist

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [ ] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

2024-07-08 01:49 UTC, abrahamguo commented
Were you able to find out why this bug was happening/what was the root cause?

2024-07-08 13:59 UTC, YutongZhuu commented
> Were you able to find out why this bug was happening/what was the root cause?
```       
 const messageId =
          currentOption === 'array'
            ? isReadonlyWithGenericArrayType
              ? 'errorStringArrayReadonly'
              : 'errorStringArray'
            : 'errorStringArraySimple';
```

Here is the logic for determining which message to display. It has a currentOption of arraySimple, so the error will be ``        "Array type using '{{className}}<{{type}}>' is forbidden for simple types. Use '{{readonlyPrefix}}{{type}}[]' instead.",
``. And the ``getMessageType(type)`` function call returns string[]. That is why we have two []'s.

2024-07-09 12:28 UTC, abrahamguo commented
Looking at how `errorStringArray` and `errorStringArrayReadonly` are defined, it may be better to be consistent with that, and add a new message `errorStringArraySimpleReadonly`.

Also, the tests are no longer failing on `main`, so you can pull from there.

2024-07-11 21:30 UTC, YutongZhuu commented
> Looking at how `errorStringArray` and `errorStringArrayReadonly` are defined, it may be better to be consistent with that, and add a new message `errorStringArraySimpleReadonly`.
> 
> Also, the tests are no longer failing on `main`, so you can pull from there.

Makes sense, I update my PR soon.

2024-07-20 20:07 UTC, JoshuaKGoldberg requested changes
Thanks for starting on this (and it was nice to see conversations around it) - but it'll need to have tests to be reviewed. Could you please? 🙂

2024-07-20 20:07 UTC, JoshuaKGoldberg commented on packages/eslint-plugin/src/rules/array-type.ts
[Testing] We can't take any bugfixes to lint rules that don't have corresponding unit tests. Could you please add to `array-type.test.ts`?

2024-07-21 14:55 UTC, YutongZhuu commented on packages/eslint-plugin/src/rules/array-type.ts
Sure, I will update the PR.

2024-07-21 17:23 UTC, YutongZhuu commented on packages/eslint-plugin/src/rules/array-type.ts
Hi, I've added a test case for this scenario, pls review.

2024-07-25 15:22 UTC, YutongZhuu commented
> Thanks for starting on this (and it was nice to see conversations around it) - but it'll need to have tests to be reviewed. Could you please? 🙂

@JoshuaKGoldberg Hi, I have added a test as requested, I see this PR has not been reviewed yet, does it mean there is something else I need to do, or you guys simply do not have time yet?

2024-07-26 16:54 UTC, auvred commented
As per [our contributing guidelines](https://typescript-eslint.io/contributing/pull-requests#addressing-feedback-and-beyond) this PR is in the queue of PRs to review, and will be reviewed when we are able.

This project is run by volunteer maintainers, so it might be a bit before we can find the time to get to it.

2024-07-26 17:02 UTC, YutongZhuu commented
> As per [our contributing guidelines](https://typescript-eslint.io/contributing/pull-requests#addressing-feedback-and-beyond) this PR is in the queue of PRs to review, and will be reviewed when we are able.
> 
> 
> 
> This project is run by volunteer maintainers, so it might be a bit before we can find the time to get to it.

No, problem. I am just making sure I am not doing anything that prevents you from reviewing it.

2024-08-14 16:33 UTC, JoshuaKGoldberg approved these changes
👍 LGTM, thanks!

![Mr Bean giving a weirdly enthusiastic thumbs up](https://github.com/user-attachments/assets/75606e79-0b6d-47e9-9676-62d4ddb15f6f)

2024-08-14 19:08 UTC, YutongZhuu commented
> CI / Lint with build (lint) (pull_request)
is not successful, something I need to fix?

2024-08-14 19:21 UTC, JoshuaKGoldberg commented
Oh yeah don't worry about that, #9794.

2024-08-19 11:14 UTC, merged