docs(eslint-plugin): [strict-boolean-expressions] fix nullable number example
typescript-eslint/typescript-eslint pull request #9702
Opened 2024-08-02 04:13 UTC by scarf005

## PR Checklist

- [x] Addresses an existing open issue: fixes #9699
- [ ] ~That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)~ [(extremely minor documentation typos)](https://typescript-eslint.io/contributing/pull-requests)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

https://typescript-eslint.io/rules/strict-boolean-expressions/#examples

fixes incorrect example not actually being incorrect, due to [typescript type narrowing](https://github.com/typescript-eslint/typescript-eslint/issues/9699#issuecomment-2264352992)

2024-08-02 07:47 UTC, kirkwaiblinger requested changes
Thanks for sending this in!

To fix the CI failure, you'll need to [regenerate the example snapshots ](https://typescript-eslint.io/contributing/local-development#rule-development) (incidentally - the whole point of that CI check is to avoid the examples becoming out of date in the first place... wish that we'd had that in place sooner!)

2024-08-02 07:47 UTC, kirkwaiblinger commented on packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
While you're here, do you mind fixing the `str` example, too? 🙏 

***

Additionally, a couple choices for your consideration
- Note that the bottom `maybeString` uses `Math.random()` - that's another way of actually getting the type of the variable to be what you want rather than `declare`. 
- There's not really any reason to use `let`, since it does the narrowing anyway. So feel free to use `declare const` if you prefer that, too 🤷 

Anyway, the way you currently have it, or any other way within the above options are all fine 🙂.

2024-08-02 07:57 UTC, scarf005 commented on packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
hi, i applied the fixes in [`539773b` (declare const for number and string example)](https://github.com/typescript-eslint/typescript-eslint/pull/9702/commits/539773bd239c1b3a32e89405033a5d04ddc19ce5) and [`24cb76a` (snapshot)](https://github.com/typescript-eslint/typescript-eslint/pull/9702/commits/24cb76acaecbc9b64071c0b4925851672f564d04)

2024-08-05 22:28 UTC, JoshuaKGoldberg approved these changes
Lovely! 💕

2024-08-05 22:28 UTC, merged