chore: replace globby with tinyglobby
typescript-eslint/typescript-eslint pull request #9878
Opened 2024-08-23 23:33 UTC by benmccann

## PR Checklist

- [x] Addresses an existing open issue: fixes https://github.com/typescript-eslint/typescript-eslint/issues/9453
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Replaces `globby` with `tinyglobby` for a smaller more efficient implementation with fewer dependencies

2024-08-24 03:54 UTC, bradzacher requested changes

2024-08-24 03:54 UTC, bradzacher commented on packages/typescript-estree/tests/lib/parse.test.ts
>    const globby = jest.requireActual<typeof globbyModule>('globby');
This would also need to change

2024-08-24 04:07 UTC, benmccann commented on packages/typescript-estree/tests/lib/parse.test.ts
>    const globby = jest.requireActual<typeof globbyModule>('globby');
done. thanks!

2024-08-24 05:26 UTC, Josh-Cena commented
Why do we have both this and https://github.com/typescript-eslint/typescript-eslint/pull/9518?

2024-08-24 13:24 UTC, benmccann commented
Oh, thanks for pointing that out. I hadn't seen it. I think `tinyglobby` is better as it has many fewer dependencies, but that PR is passing the CI whereas this one isn't. I'll check if the author is able to switch to `tinyglobby` in the other PR and if so perhaps we can close this one

2024-08-24 17:19 UTC, SukkaW commented
It seems that your CI failed due to incorrect spying of glob functions. Might wanna check that out.

2024-08-24 18:29 UTC, benmccann commented
> I just want to point out that this change added 2 new dependencies to the project and did not actually remove any included dep, if you check yarn.lock. So this feels kinda pointless change this time.
(note, I’m just a user of this plugin, so my opinions do not reflect what the maintainers may think)

The `yarn.lock` isn't what's important here because it includes both dependencies and `devDependencies`. `globby` remains only for developers of this project. If you look at where it's used now it's in things like docusaurus. This PR would remove about 40% of dependencies for all consumers of `typescript-eslint` going from 44 down to 26

2024-08-24 18:52 UTC, benmccann commented
> It seems that your CI failed due to incorrect spying of glob functions. Might wanna check that out.

I found the line I missed updating before. It's now correctly mocking. However, it's returning things in a different order. I think we basically have to combine our two PRs to get it working

2024-08-25 01:21 UTC, SukkaW commented
> However, it's returning things in a different order.

See https://github.com/typescript-eslint/typescript-eslint/pull/9518#issuecomment-2308461397

2024-08-26 00:35 UTC, bradzacher commented
As per https://github.com/typescript-eslint/typescript-eslint/issues/9453#issuecomment-2309080805 we're going to go with #9518 for now.
We may revisit this in future and switch from `fast-glob` to `tinyglobby`.

2024-08-26 00:35 UTC, closed without merging