chore: enable `unicorn/prefer-native-coercion-functions`
typescript-eslint/typescript-eslint pull request #9909
Opened 2024-09-02 22:02 UTC by abrahamguo

## PR Checklist

- [x] Addresses an existing open issue: fixes part of #9623
- [x] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken

## Overview

Enable `unicorn/prefer-native-coercion-functions` ([docs](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v55.0.0/docs/rules/prefer-native-coercion-functions.md)). 100% autofixable.

2024-09-02 22:52 UTC, bradzacher reviewed
With the latest TS version and its implementation of automatic type guards - this rule is actually potentially harmful to our codebase. So I'm a -1 on it.

2024-09-02 23:13 UTC, JoshuaKGoldberg commented on packages/website/src/components/RulesTable/index.tsx
> +        return opinions.every(Boolean);
:( the change is objectively good but `o => o` is such a cute little face

2024-09-02 23:13 UTC, JoshuaKGoldberg approved these changes
rip little `o => o` friend

2024-09-02 23:14 UTC, JoshuaKGoldberg requested changes
oh Brad is right :)

2024-09-03 02:22 UTC, abrahamguo commented
Makes sense, it's not TS aware and definitely makes less sense now that inferred type guards have landed 👍

2024-09-03 02:22 UTC, closed without merging